## Data Cleaning and Temporal harmonization

### 2.1. Prices dataset
For reducing granularity and make time series analysis easier, it is better to integrate period data (2021-2025) in the same table.

In [1]:
# import libraries
import pandas as pd
from pathlib import Path
import warnings

# filter User and Filter Warnings for privacy matters
warnings.simplefilter(action="ignore", category=UserWarning)
warnings.simplefilter(action="ignore", category=FutureWarning)

In [3]:
# define initial variables
dataset_path = Path('../dataset/raw/gme/prices/PZ')
YEARS = range(2015, 2027)

# create prices dataframe
prices_dfs = [
    pd.read_excel(
        dataset_path / f'GME-PZ-{year}.xlsx', 
        decimal=','
    )
    for year in YEARS
]

prices_data = pd.concat(prices_dfs, ignore_index=True)

prices_data

In [4]:
prices_data

,Data,Ora,Italia,Italia (senza vincoli),Austria,Calabria,Centro Nord,Corsica AC,Corsica,Centro Sud,...,Sud,Svizzera,Slovenia Coupling,Francia Coupling,Austria Coupling,Malta,Montenegro,Grecia Coupling,Italia Coupling,Note
0,01/01/2015,1,52.32756,49.9400,51.10000,NaN,51.10000,51.10000,51.10000,51.10000,...,51.10000,51.10000,51.10000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN
1,01/01/2015,2,49.89278,44.6700,49.00000,NaN,49.00000,49.00000,49.00000,49.00000,...,49.00000,49.00000,49.00000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN
2,01/01/2015,3,39.10000,38.8500,39.10000,NaN,39.10000,39.10000,39.10000,39.10000,...,39.10000,39.10000,39.10000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN
3,01/01/2015,4,35.87000,35.3300,35.87000,NaN,35.87000,35.87000,35.87000,35.87000,...,35.87000,35.87000,35.87000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN
4,01/01/2015,5,33.40000,31.0000,33.40000,NaN,33.40000,33.40000,33.40000,33.40000,...,33.40000,33.40000,33.40000,0.00000,0.00000,0.00000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100770,30/06/2026,20,204.10622,186.0950,204.10622,204.10622,204.10622,204.10622,204.10622,204.10622,...,204.10622,204.10622,204.10622,204.10622,204.10622,204.10622,204.10622,204.10622,204.10622,NaN
100771,30/06/2026,21,198.16000,185.6400,198.16000,198.16000,198.16000,198.16000,198.16000,198.16000,...,198.16000,198.16000,198.16000,198.16000,198.16000,198.16000,198.16000,198.16000,198.16000,NaN
100772,30/06/2026,22,182.03250,177.0350,182.03250,182.03250,182.03250,182.03250,182.03250,182.03250,...,182.03250,182.03250,182.03250,182.03250,182.03250,182.03250,182.03250,182.03250,182.03250,NaN
100773,30/06/2026,23,173.30306,173.9350,173.30306,173.30306,173.30306,173.30306,173.30306,173.30306,...,173.30306,173.30306,173.30306,173.30306,173.30306,173.30306,173.30306,173.30306,173.30306,NaN
100774,30/06/2026,24,143.59250,162.2075,143.59250,143.59250,143.59250,143.59250,143.59250,143.59250,...,143.59250,143.59250,143.59250,143.59250,143.59250,143.59250,143.59250,143.59250,143.59250,NaN

In [7]:
prices_data.shape

(100775, 26)

In [9]:
# check what to clean
prices_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 26 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Data                    100775 non-null  str
 1   Ora                     100775 non-null  int64
 2   Italia                  100775 non-null  float64
 3   Italia (senza vincoli)  100775 non-null  float64
 4   Austria                 100775 non-null  float64
 5   Calabria                48167 non-null   float64
 6   Centro Nord             100775 non-null  float64
 7   Corsica AC              100775 non-null  float64
 8   Corsica                 100775 non-null  float64
 9   Centro Sud              100775 non-null  float64
 10  Francia                 100775 non-null  float64
 11  Grecia                  100775 non-null  float64
 12  Nord                    100775 non-null  float64
 13  Sardegna                100775 non-null  float64
 14  Sicilia                 100775 non-null  float64
 15  Slovenia                100775 non-null  float64
 16  Sud                     100775 non-null  float64
 17  Svizzera                100775 non-null  float64
 18  Slovenia Coupling       100775 non-null  float64
 19  Francia Coupling        100775 non-null  float64
 20  Austria Coupling        100775 non-null  float64
 21  Malta                   100775 non-null  float64
 22  Montenegro              65711 non-null   float64
 23  Grecia Coupling         56951 non-null   float64
 24  Italia  Coupling        48167 non-null   float64
 25  Note                    0 non-null       float64
dtypes: float64(24), int64(1), str(1)
memory usage: 20.0 MB

In [ ]:
prices_data['Data'].describe()

count         100775
unique          4199
top       25/10/2015
freq              25
Name: Data, dtype: object

In [11]:
prices_data['Ora'].describe()

count    100775.000000
mean         12.499995
std           6.922350
min           1.000000
25%           6.500000
50%          12.000000
75%          18.000000
max          25.000000
Name: Ora, dtype: float64

In [13]:
prices_data[prices_data.columns[2:]].describe()

,Italia,Italia (senza vincoli),Austria,Calabria,Centro Nord,Corsica AC,Corsica,Centro Sud,Francia,Grecia,...,Sud,Svizzera,Slovenia Coupling,Francia Coupling,Austria Coupling,Malta,Montenegro,Grecia Coupling,Italia Coupling,Note
count,100775.000000,100775.000000,100775.000000,48167.000000,100775.000000,100775.000000,100775.000000,100775.000000,100775.000000,100775.000000,...,100775.000000,100775.000000,100775.000000,100775.000000,100775.000000,100775.000000,65711.000000,56951.000000,48167.000000,0.0
mean,99.641645,99.967792,99.786461,150.421878,100.151910,96.450886,234.388303,98.785653,99.786461,97.234187,...,97.234187,99.786461,99.786461,108.393933,108.393933,135.996758,119.739578,127.928438,143.506804,NaN
std,87.478509,97.465179,89.032714,97.886591,89.136475,85.244316,518.941760,86.519586,89.032714,85.994885,...,85.994885,89.032714,89.032714,184.289029,184.289029,319.447686,115.814545,105.423660,113.104442,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,47.337550,46.970000,46.770000,99.485000,46.870000,45.535000,48.680000,46.630000,46.770000,45.500000,...,45.500000,46.770000,46.770000,46.290000,46.290000,51.200000,47.215000,74.320000,95.465000,NaN
50%,68.860000,68.050000,69.060000,122.690000,69.060000,65.420000,74.990000,67.590000,69.060000,65.680000,...,65.680000,69.060000,69.060000,69.530000,69.530000,82.350000,105.760000,113.650000,120.873460,NaN
75%,120.255035,121.725000,120.060000,169.450000,120.845000,119.990000,136.070000,120.660000,120.060000,120.000000,...,120.000000,120.060000,120.060000,120.800000,120.800000,127.375000,146.000000,155.000000,170.000000,NaN
max,870.000000,3000.000000,871.000000,870.000000,871.000000,1000.000000,3500.000000,870.000000,871.000000,870.000000,...,870.000000,871.000000,871.000000,3000.000000,3000.000000,3000.000000,1250.000000,870.000000,871.000000,NaN

In [14]:
# Days with more than 24 hourly periods
daily_periods = (
    prices_data
    .groupby('Data')['Ora']
    .agg(['count', 'min', 'max'])
)

daily_periods[daily_periods['count'] != 24]

            count  min  max
Data
25/03/2018     23    1   23
25/10/2015     25    1   25
25/10/2020     25    1   25
26/03/2017     23    1   23
26/03/2023     23    1   23
26/10/2025     25    1   25
27/03/2016     23    1   23
27/03/2022     23    1   23
27/10/2019     25    1   25
27/10/2024     25    1   25
28/03/2021     23    1   23
28/10/2018     25    1   25
29/03/2015     23    1   23
29/03/2020     23    1   23
29/03/2026     23    1   23
29/10/2017     25    1   25
29/10/2023     25    1   25
30/03/2025     23    1   23
30/10/2016     25    1   25
30/10/2022     25    1   25
31/03/2019     23    1   23
31/03/2024     23    1   23
31/10/2021     25    1   25

In [15]:
daily_periods['count'].value_counts().sort_index()

count
23      12
24    4176
25      11
Name: count, dtype: int64

In [16]:
prices_data[
    prices_data['Data'].isin(
        daily_periods.query('count != 24').index
    )
][['Data', 'Ora', 'Italia']]

             Data  Ora     Italia
2088   29/03/2015    1   43.41000
2089   29/03/2015    2   30.17000
2090   29/03/2015    3   21.93526
2091   29/03/2015    4   30.17000
2092   29/03/2015    5   39.21005
...           ...  ...        ...
98538  29/03/2026   19  174.74686
98539  29/03/2026   20  180.25270
98540  29/03/2026   21  189.41976
98541  29/03/2026   22  182.53274
98542  29/03/2026   23  141.57235

[551 rows x 3 columns]

In [17]:
# 1. Convert date
prices_data['Data'] = pd.to_datetime(
    prices_data['Data'],
    dayfirst=True,
    errors='coerce'
)

# 2. DO NOT correct Ora yet

# 3. Inspect the number of periods per day
daily_periods = (
    prices_data
    .groupby('Data')['Ora']
    .agg(['count', 'min', 'max'])
)

print(daily_periods['count'].value_counts().sort_index())

# 4. Inspect non-standard days
print(
    prices_data[
        prices_data['Data'].isin(
            daily_periods.query('count != 24').index
        )
    ][['Data', 'Ora', 'Italia']]
)

count
23      12
24    4176
25      11
Name: count, dtype: int64
            Data  Ora     Italia
2088  2015-03-29    1   43.41000
2089  2015-03-29    2   30.17000
2090  2015-03-29    3   21.93526
2091  2015-03-29    4   30.17000
2092  2015-03-29    5   39.21005
...          ...  ...        ...
98538 2026-03-29   19  174.74686
98539 2026-03-29   20  180.25270
98540 2026-03-29   21  189.41976
98541 2026-03-29   22  182.53274
98542 2026-03-29   23  141.57235

[551 rows x 3 columns]

In [18]:
# Spring DST transition
spring_dates = daily_periods.query('count == 23').index

for date in spring_dates:
    print(f'\n--- {date} ---')
    print(
        prices_data.loc[
            prices_data['Data'] == date,
            ['Data', 'Ora', 'Italia']
        ].to_string(index=False)
    )

--- 2015-03-29 00:00:00 ---
      Data  Ora   Italia
2015-03-29    1 43.41000
2015-03-29    2 30.17000
2015-03-29    3 21.93526
2015-03-29    4 30.17000
2015-03-29    5 39.21005
2015-03-29    6 39.69000
2015-03-29    7 40.10870
2015-03-29    8 36.83477
2015-03-29    9 37.19705
2015-03-29   10 38.54698
2015-03-29   11 30.86035
2015-03-29   12 29.12214
2015-03-29   13 25.00698
2015-03-29   14 27.02504
2015-03-29   15 29.10313
2015-03-29   16 42.08931
2015-03-29   17 43.93000
2015-03-29   18 52.87223
2015-03-29   19 60.08687
2015-03-29   20 57.27031
2015-03-29   21 50.46143
2015-03-29   22 46.55000
2015-03-29   23 39.48899

--- 2016-03-27 00:00:00 ---
      Data  Ora   Italia
2016-03-27    1 38.98469
2016-03-27    2 37.16789
2016-03-27    3 34.50000
2016-03-27    4 34.50000
2016-03-27    5 34.00000
2016-03-27    6 34.47954
2016-03-27    7 34.48686
2016-03-27    8 35.83867
2016-03-27    9 34.61465
2016-03-27   10 33.08211
2016-03-27   11 31.39698
2016-03-27   12 21.85411
2016-03-27   13 15.60120
2016-03-27   14 10.94038
2016-03-27   15 19.20000
2016-03-27   16 27.62017
2016-03-27   17 33.60694
2016-03-27   18 38.96283
2016-03-27   19 45.62796
2016-03-27   20 52.59150
2016-03-27   21 46.07628
2016-03-27   22 39.11561
2016-03-27   23 36.84980

--- 2017-03-26 00:00:00 ---
      Data  Ora   Italia
2017-03-26    1 40.91620
2017-03-26    2 37.37000
2017-03-26    3 36.00000
2017-03-26    4 36.68000
2017-03-26    5 39.21000
2017-03-26    6 38.15000
2017-03-26    7 38.20000
2017-03-26    8 40.30030
2017-03-26    9 40.81903
2017-03-26   10 42.96780
2017-03-26   11 39.11000
2017-03-26   12 37.24049
2017-03-26   13 33.72146
2017-03-26   14 32.95177
2017-03-26   15 34.93000
2017-03-26   16 36.99000
2017-03-26   17 39.40000
2017-03-26   18 45.41000
2017-03-26   19 50.35123
2017-03-26   20 50.13478
2017-03-26   21 48.71091
2017-03-26   22 46.81871
2017-03-26   23 41.18191

--- 2018-03-25 00:00:00 ---
      Data  Ora   Italia
2018-03-25    1 46.74000
2018-03-25    2 46.00000
2018-03-25    3 37.85163
2018-03-25    4 37.43000
2018-03-25    5 42.95105
2018-03-25    6 42.24000
2018-03-25    7 43.67000
2018-03-25    8 46.08000
2018-03-25    9 46.08000
2018-03-25   10 46.36000
2018-03-25   11 46.17000
2018-03-25   12 45.70000
2018-03-25   13 42.10003
2018-03-25   14 37.95194
2018-03-25   15 35.60000
2018-03-25   16 39.82000
2018-03-25   17 45.01000
2018-03-25   18 51.18000
2018-03-25   19 70.00000
2018-03-25   20 70.00000
2018-03-25   21 60.63167
2018-03-25   22 54.87483
2018-03-25   23 49.39000

--- 2019-03-31 00:00:00 ---
      Data  Ora   Italia
2019-03-31    1 51.82192
2019-03-31    2 44.02772
2019-03-31    3 39.00000
2019-03-31    4 38.53000
2019-03-31    5 43.72000
2019-03-31    6 44.60000
2019-03-31    7 47.28000
2019-03-31    8 49.07000
2019-03-31    9 48.92791
2019-03-31   10 49.14160
2019-03-31   11 47.57617
2019-03-31   12 41.96600
2019-03-31   13 38.70369
2019-03-31   14 35.92271
2019-03-31   15 41.29162
2019-03-31   16 49.07000
2019-03-31   17 53.79000
2019-03-31   18 60.61174
2019-03-31   19 71.06996
2019-03-31   20 69.45808
2019-03-31   21 67.44796
2019-03-31   22 59.68314
2019-03-31   23 49.11756

--- 2020-03-29 00:00:00 ---
      Data  Ora   Italia
2020-03-29    1 33.00000
2020-03-29    2 27.68000
2020-03-29    3 25.80000
2020-03-29    4 25.50000
2020-03-29    5 27.12000
2020-03-29    6 27.31000
2020-03-29    7 27.74000
2020-03-29    8 27.68000
2020-03-29    9 27.10000
2020-03-29   10 25.50000
2020-03-29   11 25.00000
2020-03-29   12 23.43000
2020-03-29   13 18.94913
2020-03-29   14 17.00000
2020-03-29   15 20.00000
2020-03-29   16 24.90000
2020-03-29   17 27.71000
2020-03-29   18 33.53000
2020-03-29   19 44.64000
2020-03-29   20 44.64000
2020-03-29   21 39.96000
2020-03-29   22 38.00000
2020-03-29   23 31.75000

--- 2021-03-28 00:00:00 ---
      Data  Ora   Italia
2021-03-28    1 63.84769
2021-03-28    2 56.87946
2021-03-28    3 54.69000
2021-03-28    4 54.89000
2021-03-28    5 61.13000
2021-03-28    6 61.47000
2021-03-28    7 62.43000
2021-03-28    8 61.13000
2021-03-28    9 63.47000
2021-03-28   10 66.07000
2021-03-28   11 59.47000
2021-03-28   12 53.90000
2021-03-28   13 51.67000
2021-03-28   14 46.40000
2021-03-28   15 46.80000
2021-03-28   16 52.36000
2021-03-28   17 64.41000
2021-03-28   18 77.45628
2021-03-28   19 87.00162
2021-03-28   20 89.68714
2021-03-28   21 82.21154
2021-03-28   22 75.04972
2021-03-28   23 62.82049

--- 2022-03-27 00:00:00 ---
      Data  Ora    Italia
2022-03-27    1 235.00000
2022-03-27    2 221.93000
2022-03-27    3 214.01906
2022-03-27    4 212.00151
2022-03-27    5 211.09000
2022-03-27    6 210.31000
2022-03-27    7 214.03054
2022-03-27    8 214.08145
2022-03-27    9 214.07340
2022-03-27   10 205.01966
2022-03-27   11 197.61000
2022-03-27   12 192.08000
2022-03-27   13 157.80811
2022-03-27   14  93.99000
2022-03-27   15  94.99000
2022-03-27   16 141.58754
2022-03-27   17 194.83000
2022-03-27   18 220.00000
2022-03-27   19 262.98281
2022-03-27   20 285.00000
2022-03-27   21 275.11662
2022-03-27   22 254.00199
2022-03-27   23 235.58000

--- 2023-03-26 00:00:00 ---
      Data  Ora    Italia
2023-03-26    1 132.10000
2023-03-26    2 126.88000
2023-03-26    3 125.86000
2023-03-26    4 116.00000
2023-03-26    5 124.71000
2023-03-26    6 127.13000
2023-03-26    7 128.72000
2023-03-26    8 128.00000
2023-03-26    9 102.25000
2023-03-26   10  79.51185
2023-03-26   11  51.03864
2023-03-26   12  32.51833
2023-03-26   13  32.74543
2023-03-26   14  34.76866
2023-03-26   15  34.20273
2023-03-26   16  40.43716
2023-03-26   17  97.32650
2023-03-26   18 133.95000
2023-03-26   19 194.77000
2023-03-26   20 195.93000
2023-03-26   21 179.10000
2023-03-26   22 145.00000
2023-03-26   23 131.00000

--- 2024-03-31 00:00:00 ---
      Data  Ora    Italia
2024-03-31    1  93.77000
2024-03-31    2  95.00000
2024-03-31    3  95.24000
2024-03-31    4  95.00000
2024-03-31    5  95.46000
2024-03-31    6  95.52000
2024-03-31    7  96.38000
2024-03-31    8  96.38000
2024-03-31    9  94.07000
2024-03-31   10  91.02000
2024-03-31   11  74.99638
2024-03-31   12  50.56283
2024-03-31   13  32.78476
2024-03-31   14   2.20053
2024-03-31   15   8.88454
2024-03-31   16  59.00000
2024-03-31   17  95.52000
2024-03-31   18 102.94000
2024-03-31   19 124.02000
2024-03-31   20 134.90000
2024-03-31   21 127.34000
2024-03-31   22 111.20000
2024-03-31   23  99.44000

--- 2025-03-30 00:00:00 ---
      Data  Ora    Italia
2025-03-30    1 126.00000
2025-03-30    2 116.50000
2025-03-30    3 112.52000
2025-03-30    4 105.97000
2025-03-30    5 108.19000
2025-03-30    6 109.00000
2025-03-30    7 108.31000
2025-03-30    8 106.50000
2025-03-30    9 103.66000
2025-03-30   10  55.00000
2025-03-30   11  49.47061
2025-03-30   12  29.68591
2025-03-30   13  17.75636
2025-03-30   14   9.85918
2025-03-30   15  13.95815
2025-03-30   16  24.40000
2025-03-30   17  92.33000
2025-03-30   18 126.00000
2025-03-30   19 140.00000
2025-03-30   20 139.23000
2025-03-30   21 131.96000
2025-03-30   22 127.35000
2025-03-30   23 119.79000

--- 2026-03-29 00:00:00 ---
      Data  Ora    Italia
2026-03-29    1 168.82000
2026-03-29    2 143.23000
2026-03-29    3 134.07000
2026-03-29    4 136.62000
2026-03-29    5 139.27000
2026-03-29    6 163.16793
2026-03-29    7 174.19357
2026-03-29    8 147.74149
2026-03-29    9 123.93874
2026-03-29   10  99.69125
2026-03-29   11  46.70434
2026-03-29   12  38.64266
2026-03-29   13  25.93892
2026-03-29   14  15.16293
2026-03-29   15  10.24617
2026-03-29   16  20.79075
2026-03-29   17  92.31182
2026-03-29   18 140.40446
2026-03-29   19 174.74686
2026-03-29   20 180.25270
2026-03-29   21 189.41976
2026-03-29   22 182.53274
2026-03-29   23 141.57235

In [19]:
# Autumn DST transition
autumn_dates = daily_periods.query('count == 25').index

for date in autumn_dates:
    print(f'\n--- {date} ---')
    print(
        prices_data.loc[
            prices_data['Data'] == date,
            ['Data', 'Ora', 'Italia']
        ].to_string(index=False)
    )

--- 2015-10-25 00:00:00 ---
      Data  Ora   Italia
2015-10-25    1 44.49129
2015-10-25    2 39.50519
2015-10-25    3 34.99000
2015-10-25    4 36.66960
2015-10-25    5 32.64779
2015-10-25    6 32.92109
2015-10-25    7 36.65610
2015-10-25    8 37.26000
2015-10-25    9 36.62085
2015-10-25   10 34.97185
2015-10-25   11 38.37575
2015-10-25   12 42.44287
2015-10-25   13 40.77699
2015-10-25   14 41.33082
2015-10-25   15 39.30921
2015-10-25   16 41.17682
2015-10-25   17 43.30207
2015-10-25   18 50.51839
2015-10-25   19 52.50332
2015-10-25   20 55.34951
2015-10-25   21 58.59309
2015-10-25   22 51.09558
2015-10-25   23 46.30488
2015-10-25   24 44.15833
2015-10-25   25 42.87699

--- 2016-10-30 00:00:00 ---
      Data  Ora   Italia
2016-10-30    1 53.72890
2016-10-30    2 49.60206
2016-10-30    3 48.31807
2016-10-30    4 47.17238
2016-10-30    5 43.24685
2016-10-30    6 43.88613
2016-10-30    7 46.96103
2016-10-30    8 45.54098
2016-10-30    9 46.74697
2016-10-30   10 45.99397
2016-10-30   11 44.76000
2016-10-30   12 46.25202
2016-10-30   13 44.92000
2016-10-30   14 44.88702
2016-10-30   15 43.50829
2016-10-30   16 46.15122
2016-10-30   17 50.28786
2016-10-30   18 53.78328
2016-10-30   19 54.72185
2016-10-30   20 59.36427
2016-10-30   21 58.53459
2016-10-30   22 57.01789
2016-10-30   23 55.13449
2016-10-30   24 52.32292
2016-10-30   25 51.07463

--- 2017-10-29 00:00:00 ---
      Data  Ora   Italia
2017-10-29    1 59.26417
2017-10-29    2 49.44908
2017-10-29    3 45.56919
2017-10-29    4 45.23391
2017-10-29    5 43.74661
2017-10-29    6 43.45563
2017-10-29    7 45.23450
2017-10-29    8 46.46904
2017-10-29    9 49.53556
2017-10-29   10 46.91102
2017-10-29   11 44.03030
2017-10-29   12 43.05496
2017-10-29   13 42.60938
2017-10-29   14 40.60936
2017-10-29   15 38.17093
2017-10-29   16 36.78755
2017-10-29   17 39.56272
2017-10-29   18 47.08008
2017-10-29   19 50.10961
2017-10-29   20 61.64738
2017-10-29   21 65.10837
2017-10-29   22 64.96844
2017-10-29   23 56.43226
2017-10-29   24 55.28038
2017-10-29   25 46.79743

--- 2018-10-28 00:00:00 ---
      Data  Ora   Italia
2018-10-28    1 64.02000
2018-10-28    2 54.83000
2018-10-28    3 52.40000
2018-10-28    4 50.12000
2018-10-28    5 45.92000
2018-10-28    6 44.00054
2018-10-28    7 44.79000
2018-10-28    8 47.27000
2018-10-28    9 50.14000
2018-10-28   10 53.89469
2018-10-28   11 54.53563
2018-10-28   12 58.51715
2018-10-28   13 58.79700
2018-10-28   14 58.77214
2018-10-28   15 56.65401
2018-10-28   16 56.59268
2018-10-28   17 57.00144
2018-10-28   18 60.51349
2018-10-28   19 58.90772
2018-10-28   20 65.02000
2018-10-28   21 69.14000
2018-10-28   22 66.03000
2018-10-28   23 64.02000
2018-10-28   24 64.00000
2018-10-28   25 60.00000

--- 2019-10-27 00:00:00 ---
      Data  Ora   Italia
2019-10-27    1 38.97430
2019-10-27    2 36.64000
2019-10-27    3 35.36585
2019-10-27    4 35.05352
2019-10-27    5 34.05375
2019-10-27    6 34.05559
2019-10-27    7 34.06309
2019-10-27    8 36.12690
2019-10-27    9 35.43078
2019-10-27   10 35.99110
2019-10-27   11 36.24164
2019-10-27   12 34.99000
2019-10-27   13 33.83000
2019-10-27   14 35.19000
2019-10-27   15 34.55000
2019-10-27   16 35.87000
2019-10-27   17 40.44477
2019-10-27   18 44.22230
2019-10-27   19 50.95429
2019-10-27   20 62.49638
2019-10-27   21 63.58419
2019-10-27   22 61.69191
2019-10-27   23 50.68258
2019-10-27   24 43.49161
2019-10-27   25 37.73780

--- 2020-10-25 00:00:00 ---
      Data  Ora   Italia
2020-10-25    1 35.00000
2020-10-25    2 32.30000
2020-10-25    3 25.00000
2020-10-25    4 24.63000
2020-10-25    5 24.63000
2020-10-25    6 21.88000
2020-10-25    7 23.03383
2020-10-25    8 33.94274
2020-10-25    9 22.64112
2020-10-25   10 29.33000
2020-10-25   11 28.35000
2020-10-25   12 28.87000
2020-10-25   13 26.87000
2020-10-25   14 31.45000
2020-10-25   15 25.91000
2020-10-25   16 31.10000
2020-10-25   17 32.30000
2020-10-25   18 39.25158
2020-10-25   19 45.38910
2020-10-25   20 48.33434
2020-10-25   21 50.23229
2020-10-25   22 45.58475
2020-10-25   23 43.62696
2020-10-25   24 42.32999
2020-10-25   25 37.00000

--- 2021-10-31 00:00:00 ---
      Data  Ora    Italia
2021-10-31    1 205.70366
2021-10-31    2 183.88086
2021-10-31    3 188.24140
2021-10-31    4 191.25335
2021-10-31    5 184.78900
2021-10-31    6 184.77937
2021-10-31    7 184.76506
2021-10-31    8 191.16432
2021-10-31    9 180.69198
2021-10-31   10 183.84324
2021-10-31   11 180.88305
2021-10-31   12 184.98703
2021-10-31   13 184.88932
2021-10-31   14 188.56276
2021-10-31   15 178.45303
2021-10-31   16 178.08320
2021-10-31   17 175.76828
2021-10-31   18 191.05121
2021-10-31   19 221.01525
2021-10-31   20 235.34688
2021-10-31   21 242.64075
2021-10-31   22 231.59213
2021-10-31   23 222.18241
2021-10-31   24 191.30084
2021-10-31   25 172.71579

--- 2022-10-30 00:00:00 ---
      Data  Ora    Italia
2022-10-30    1 103.20000
2022-10-30    2 100.55000
2022-10-30    3 100.25000
2022-10-30    4 100.14777
2022-10-30    5  98.41000
2022-10-30    6  98.50000
2022-10-30    7  98.98000
2022-10-30    8 100.55000
2022-10-30    9 101.80000
2022-10-30   10  98.50000
2022-10-30   11  98.34000
2022-10-30   12  97.36000
2022-10-30   13  94.01734
2022-10-30   14  95.43000
2022-10-30   15  98.34000
2022-10-30   16  98.49449
2022-10-30   17 103.14000
2022-10-30   18 114.99000
2022-10-30   19 156.00000
2022-10-30   20 170.38178
2022-10-30   21 165.00000
2022-10-30   22 147.52323
2022-10-30   23 139.08159
2022-10-30   24 119.99000
2022-10-30   25 102.50000

--- 2023-10-29 00:00:00 ---
      Data  Ora    Italia
2023-10-29    1 120.39000
2023-10-29    2 105.41000
2023-10-29    3 110.00000
2023-10-29    4 113.00000
2023-10-29    5 103.94000
2023-10-29    6  89.00000
2023-10-29    7  90.00000
2023-10-29    8 114.98000
2023-10-29    9 120.40000
2023-10-29   10 124.78000
2023-10-29   11 120.36000
2023-10-29   12 100.49000
2023-10-29   13 100.00000
2023-10-29   14 105.00000
2023-10-29   15  95.00000
2023-10-29   16 110.00000
2023-10-29   17 127.81000
2023-10-29   18 140.03047
2023-10-29   19 154.19268
2023-10-29   20 160.00000
2023-10-29   21 168.42380
2023-10-29   22 159.01004
2023-10-29   23 141.95362
2023-10-29   24 121.57756
2023-10-29   25 138.91204

--- 2024-10-27 00:00:00 ---
      Data  Ora    Italia
2024-10-27    1  97.71000
2024-10-27    2  99.28000
2024-10-27    3  95.35000
2024-10-27    4  97.64000
2024-10-27    5 105.10000
2024-10-27    6 107.26000
2024-10-27    7 105.90000
2024-10-27    8 106.92000
2024-10-27    9 115.93000
2024-10-27   10 109.18000
2024-10-27   11 106.81000
2024-10-27   12 117.45000
2024-10-27   13 110.00000
2024-10-27   14 109.97000
2024-10-27   15 105.10000
2024-10-27   16 105.10000
2024-10-27   17 116.36501
2024-10-27   18 130.00000
2024-10-27   19 141.72332
2024-10-27   20 146.10309
2024-10-27   21 142.92000
2024-10-27   22 131.44000
2024-10-27   23 122.04099
2024-10-27   24 116.20894
2024-10-27   25 110.00000

--- 2025-10-26 00:00:00 ---
      Data  Ora    Italia
2025-10-26    1  94.13000
2025-10-26    2  89.90000
2025-10-26    3  85.79000
2025-10-26    4  85.76000
2025-10-26    5  77.09828
2025-10-26    6  73.74328
2025-10-26    7  85.77000
2025-10-26    8  92.22799
2025-10-26    9  85.78000
2025-10-26   10  55.33794
2025-10-26   11  42.56046
2025-10-26   12  52.16146
2025-10-26   13  50.27655
2025-10-26   14  30.64342
2025-10-26   15  54.47883
2025-10-26   16  65.09901
2025-10-26   17  88.72267
2025-10-26   18 105.10000
2025-10-26   19 115.00000
2025-10-26   20 119.64351
2025-10-26   21 124.83212
2025-10-26   22 117.94183
2025-10-26   23 112.00000
2025-10-26   24  99.44527
2025-10-26   25  85.26890

In [20]:
prices_data['datetime'] = (
    prices_data['Data']
    + pd.to_timedelta(prices_data['Ora'] - 1, unit='h')
)

diffs = prices_data['datetime'].diff()

diffs.value_counts().sort_index()

datetime
0 days 00:00:00        11
0 days 01:00:00    100751
0 days 02:00:00        12
Name: count, dtype: int64

Source: https://gme.mercatoelettrico.org/Portals/0/Documents/it-IT/20250101DTF01rev3MPE.pdf

In [21]:
# Make a copy
prices_data = prices_data.copy()

# Convert Date
prices_data['Date'] = pd.to_datetime(
    prices_data['Data'],
    dayfirst=True,
    errors='coerce'
)

# Make sure Ora is numeric
prices_data['Ora'] = pd.to_numeric(
    prices_data['Ora'],
    errors='coerce'
)

In [22]:
periods_per_day = (
    prices_data
    .groupby('Date')['Ora']
    .transform('count')
)

prices_data['periods_per_day'] = periods_per_day

In [23]:
def gme_local_datetime(row):
    
    date = row['Date']
    hour = row['Ora']
    periods = row['periods_per_day']

    # Normal day: 24 periods
    if periods == 24:
        return date + pd.to_timedelta(hour - 1, unit='h')

    # Spring DST: 23 periods
    # Ora 1 = 00:00
    # Ora 2 = 01:00
    # Ora 3 = 03:00
    # ...
    elif periods == 23:
        if hour >= 3:
            return date + pd.to_timedelta(hour, unit='h')
        else:
            return date + pd.to_timedelta(hour - 1, unit='h')

    # Autumn DST: 25 periods
    # Ora 1 = 00:00
    # Ora 2 = 01:00
    # Ora 3 = 02:00 CEST
    # Ora 4 = 02:00 CET
    # Ora 5 = 03:00 CET
    elif periods == 25:
        if hour <= 2:
            return date + pd.to_timedelta(hour - 1, unit='h')
        elif hour <= 4:
            return date + pd.Timedelta(hours=2)
        else:
            return date + pd.to_timedelta(hour - 2, unit='h')

    else:
        raise ValueError(
            f"Unexpected number of periods ({periods}) for {date}"
        )

In [24]:
prices_data['datetime_local_naive'] = prices_data.apply(
    gme_local_datetime,
    axis=1
)

In [25]:
ambiguous = (
    (prices_data['periods_per_day'] == 25)
    & (prices_data['Ora'] == 3)
)

prices_data['datetime_local'] = (
    prices_data['datetime_local_naive']
    .dt.tz_localize(
        'Europe/Rome',
        ambiguous=ambiguous,
        nonexistent='raise'
    )
)

In [26]:
prices_data['datetime_UTC'] = (
    prices_data['datetime_local']
    .dt.tz_convert('UTC')
)

In [29]:
prices_data.head()

,Data,Ora,Italia,Italia (senza vincoli),Austria,Calabria,Centro Nord,Corsica AC,Corsica,Centro Sud,...,Montenegro,Grecia Coupling,Italia Coupling,Note,datetime,Date,periods_per_day,datetime_local_naive,datetime_local,datetime_UTC
0,2015-01-01,1,52.32756,49.94,51.10,NaN,51.10,51.10,51.10,51.10,...,NaN,NaN,NaN,NaN,2015-01-01 00:00:00,2015-01-01,24,2015-01-01 00:00:00,2015-01-01 00:00:00+01:00,2014-12-31 23:00:00+00:00
1,2015-01-01,2,49.89278,44.67,49.00,NaN,49.00,49.00,49.00,49.00,...,NaN,NaN,NaN,NaN,2015-01-01 01:00:00,2015-01-01,24,2015-01-01 01:00:00,2015-01-01 01:00:00+01:00,2015-01-01 00:00:00+00:00
2,2015-01-01,3,39.10000,38.85,39.10,NaN,39.10,39.10,39.10,39.10,...,NaN,NaN,NaN,NaN,2015-01-01 02:00:00,2015-01-01,24,2015-01-01 02:00:00,2015-01-01 02:00:00+01:00,2015-01-01 01:00:00+00:00
3,2015-01-01,4,35.87000,35.33,35.87,NaN,35.87,35.87,35.87,35.87,...,NaN,NaN,NaN,NaN,2015-01-01 03:00:00,2015-01-01,24,2015-01-01 03:00:00,2015-01-01 03:00:00+01:00,2015-01-01 02:00:00+00:00
4,2015-01-01,5,33.40000,31.00,33.40,NaN,33.40,33.40,33.40,33.40,...,NaN,NaN,NaN,NaN,2015-01-01 04:00:00,2015-01-01,24,2015-01-01 04:00:00,2015-01-01 04:00:00+01:00,2015-01-01 03:00:00+00:00

In [27]:
prices_data.loc[
    prices_data['Date'] == '2015-10-25',
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'      Date  Ora            datetime_local              datetime_UTC\n2015-10-25    1 2015-10-25 00:00:00+02:00 2015-10-24 22:00:00+00:00\n2015-10-25    2 2015-10-25 01:00:00+02:00 2015-10-24 23:00:00+00:00\n2015-10-25    3 2015-10-25 02:00:00+02:00 2015-10-25 00:00:00+00:00\n2015-10-25    4 2015-10-25 02:00:00+01:00 2015-10-25 01:00:00+00:00\n2015-10-25    5 2015-10-25 03:00:00+01:00 2015-10-25 02:00:00+00:00\n2015-10-25    6 2015-10-25 04:00:00+01:00 2015-10-25 03:00:00+00:00\n2015-10-25    7 2015-10-25 05:00:00+01:00 2015-10-25 04:00:00+00:00\n2015-10-25    8 2015-10-25 06:00:00+01:00 2015-10-25 05:00:00+00:00\n2015-10-25    9 2015-10-25 07:00:00+01:00 2015-10-25 06:00:00+00:00\n2015-10-25   10 2015-10-25 08:00:00+01:00 2015-10-25 07:00:00+00:00\n2015-10-25   11 2015-10-25 09:00:00+01:00 2015-10-25 08:00:00+00:00\n2015-10-25   12 2015-10-25 10:00:00+01:00 2015-10-25 09:00:00+00:00\n2015-10-25   13 2015-10-25 11:00:00+01:00 2015-10-25 10:00:00+00:00\n2015-10-25   14 2015-10-25 12:00:00+01:00 2015-10-25 11:00:00+00:00\n2015-10-25   15 2015-10-25 13:00:00+01:00 2015-10-25 12:00:00+00:00\n2015-10-25   16 2015-10-25 14:00:00+01:00 2015-10-25 13:00:00+00:00\n2015-10-25   17 2015-10-25 15:00:00+01:00 2015-10-25 14:00:00+00:00\n2015-10-25   18 2015-10-25 16:00:00+01:00 2015-10-25 15:00:00+00:00\n2015-10-25   19 2015-10-25 17:00:00+01:00 2015-10-25 16:00:00+00:00\n2015-10-25   20 2015-10-25 18:00:00+01:00 2015-10-25 17:00:00+00:00\n2015-10-25   21 2015-10-25 19:00:00+01:00 2015-10-25 18:00:00+00:00\n2015-10-25   22 2015-10-25 20:00:00+01:00 2015-10-25 19:00:00+00:00\n2015-10-25   23 2015-10-25 21:00:00+01:00 2015-10-25 20:00:00+00:00\n2015-10-25   24 2015-10-25 22:00:00+01:00 2015-10-25 21:00:00+00:00\n2015-10-25   25 2015-10-25 23:00:00+01:00 2015-10-25 22:00:00+00:00'

In [30]:
prices_data['datetime_UTC'].diff().value_counts().head()

datetime_UTC
0 days 01:00:00    100774
Name: count, dtype: int64

In [31]:
prices_data.loc[
    prices_data['Date'].isin([
        '2015-03-29',
        '2015-10-25',
        '2015-10-26'
    ]),
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'Empty DataFrame\nColumns: [Date, Ora, datetime_local, datetime_UTC]\nIndex: []'

In [32]:
print(
    prices_data['datetime_UTC'].isna().sum()
)

0

In [33]:
prices_data = prices_data.drop(
    columns=['periods_per_day', 'datetime_local_naive']
)

In [34]:
prices_data = prices_data[
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
    + [
        col for col in prices_data.columns
        if col not in [
            'Date',
            'Ora',
            'datetime_local',
            'datetime_UTC'
        ]
    ]
]

In [35]:
prices_data[
    prices_data['Date'].dt.strftime('%Y-%m-%d') == '2015-03-29'
][['Date', 'Ora', 'datetime_local', 'datetime_UTC']]

           Date  Ora            datetime_local              datetime_UTC
2088 2015-03-29    1 2015-03-29 00:00:00+01:00 2015-03-28 23:00:00+00:00
2089 2015-03-29    2 2015-03-29 01:00:00+01:00 2015-03-29 00:00:00+00:00
2090 2015-03-29    3 2015-03-29 03:00:00+02:00 2015-03-29 01:00:00+00:00
2091 2015-03-29    4 2015-03-29 04:00:00+02:00 2015-03-29 02:00:00+00:00
2092 2015-03-29    5 2015-03-29 05:00:00+02:00 2015-03-29 03:00:00+00:00
2093 2015-03-29    6 2015-03-29 06:00:00+02:00 2015-03-29 04:00:00+00:00
2094 2015-03-29    7 2015-03-29 07:00:00+02:00 2015-03-29 05:00:00+00:00
2095 2015-03-29    8 2015-03-29 08:00:00+02:00 2015-03-29 06:00:00+00:00
2096 2015-03-29    9 2015-03-29 09:00:00+02:00 2015-03-29 07:00:00+00:00
2097 2015-03-29   10 2015-03-29 10:00:00+02:00 2015-03-29 08:00:00+00:00
2098 2015-03-29   11 2015-03-29 11:00:00+02:00 2015-03-29 09:00:00+00:00
2099 2015-03-29   12 2015-03-29 12:00:00+02:00 2015-03-29 10:00:00+00:00
2100 2015-03-29   13 2015-03-29 13:00:00+02:00 2015-03-29 11:00:00+00:00
2101 2015-03-29   14 2015-03-29 14:00:00+02:00 2015-03-29 12:00:00+00:00
2102 2015-03-29   15 2015-03-29 15:00:00+02:00 2015-03-29 13:00:00+00:00
2103 2015-03-29   16 2015-03-29 16:00:00+02:00 2015-03-29 14:00:00+00:00
2104 2015-03-29   17 2015-03-29 17:00:00+02:00 2015-03-29 15:00:00+00:00
2105 2015-03-29   18 2015-03-29 18:00:00+02:00 2015-03-29 16:00:00+00:00
2106 2015-03-29   19 2015-03-29 19:00:00+02:00 2015-03-29 17:00:00+00:00
2107 2015-03-29   20 2015-03-29 20:00:00+02:00 2015-03-29 18:00:00+00:00
2108 2015-03-29   21 2015-03-29 21:00:00+02:00 2015-03-29 19:00:00+00:00
2109 2015-03-29   22 2015-03-29 22:00:00+02:00 2015-03-29 20:00:00+00:00
2110 2015-03-29   23 2015-03-29 23:00:00+02:00 2015-03-29 21:00:00+00:00

In [36]:
prices_data.loc[
    prices_data['Date'].dt.strftime('%Y-%m-%d') == '2015-03-29',
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'      Date  Ora            datetime_local              datetime_UTC\n2015-03-29    1 2015-03-29 00:00:00+01:00 2015-03-28 23:00:00+00:00\n2015-03-29    2 2015-03-29 01:00:00+01:00 2015-03-29 00:00:00+00:00\n2015-03-29    3 2015-03-29 03:00:00+02:00 2015-03-29 01:00:00+00:00\n2015-03-29    4 2015-03-29 04:00:00+02:00 2015-03-29 02:00:00+00:00\n2015-03-29    5 2015-03-29 05:00:00+02:00 2015-03-29 03:00:00+00:00\n2015-03-29    6 2015-03-29 06:00:00+02:00 2015-03-29 04:00:00+00:00\n2015-03-29    7 2015-03-29 07:00:00+02:00 2015-03-29 05:00:00+00:00\n2015-03-29    8 2015-03-29 08:00:00+02:00 2015-03-29 06:00:00+00:00\n2015-03-29    9 2015-03-29 09:00:00+02:00 2015-03-29 07:00:00+00:00\n2015-03-29   10 2015-03-29 10:00:00+02:00 2015-03-29 08:00:00+00:00\n2015-03-29   11 2015-03-29 11:00:00+02:00 2015-03-29 09:00:00+00:00\n2015-03-29   12 2015-03-29 12:00:00+02:00 2015-03-29 10:00:00+00:00\n2015-03-29   13 2015-03-29 13:00:00+02:00 2015-03-29 11:00:00+00:00\n2015-03-29   14 2015-03-29 14:00:00+02:00 2015-03-29 12:00:00+00:00\n2015-03-29   15 2015-03-29 15:00:00+02:00 2015-03-29 13:00:00+00:00\n2015-03-29   16 2015-03-29 16:00:00+02:00 2015-03-29 14:00:00+00:00\n2015-03-29   17 2015-03-29 17:00:00+02:00 2015-03-29 15:00:00+00:00\n2015-03-29   18 2015-03-29 18:00:00+02:00 2015-03-29 16:00:00+00:00\n2015-03-29   19 2015-03-29 19:00:00+02:00 2015-03-29 17:00:00+00:00\n2015-03-29   20 2015-03-29 20:00:00+02:00 2015-03-29 18:00:00+00:00\n2015-03-29   21 2015-03-29 21:00:00+02:00 2015-03-29 19:00:00+00:00\n2015-03-29   22 2015-03-29 22:00:00+02:00 2015-03-29 20:00:00+00:00\n2015-03-29   23 2015-03-29 23:00:00+02:00 2015-03-29 21:00:00+00:00'

In [39]:
prices_data = prices_data.drop(
    columns=['Data', 'Note', 'datetime']
)

In [40]:
# final cleaning check
prices_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Date                    100775 non-null  datetime64[us]
 1   Ora                     100775 non-null  int64
 2   datetime_local          100775 non-null  datetime64[us, Europe/Rome]
 3   datetime_UTC            100775 non-null  datetime64[us, UTC]
 4   Italia                  100775 non-null  float64
 5   Italia (senza vincoli)  100775 non-null  float64
 6   Austria                 100775 non-null  float64
 7   Calabria                48167 non-null   float64
 8   Centro Nord             100775 non-null  float64
 9   Corsica AC              100775 non-null  float64
 10  Corsica                 100775 non-null  float64
 11  Centro Sud              100775 non-null  float64
 12  Francia                 100775 non-null  float64
 13  Grecia                  100775 non-null  float64
 14  Nord                    100775 non-null  float64
 15  Sardegna                100775 non-null  float64
 16  Sicilia                 100775 non-null  float64
 17  Slovenia                100775 non-null  float64
 18  Sud                     100775 non-null  float64
 19  Svizzera                100775 non-null  float64
 20  Slovenia Coupling       100775 non-null  float64
 21  Francia Coupling        100775 non-null  float64
 22  Austria Coupling        100775 non-null  float64
 23  Malta                   100775 non-null  float64
 24  Montenegro              65711 non-null   float64
 25  Grecia Coupling         56951 non-null   float64
 26  Italia  Coupling        48167 non-null   float64
dtypes: datetime64[us, Europe/Rome](1), datetime64[us, UTC](1), datetime64[us](1), float64(23), int64(1)
memory usage: 20.8 MB

In [42]:
prices_data.columns.tolist()

['Date',
 'Ora',
 'datetime_local',
 'datetime_UTC',
 'Italia',
 'Italia (senza vincoli)',
 'Austria',
 'Calabria',
 'Centro Nord',
 'Corsica AC',
 'Corsica',
 'Centro Sud',
 'Francia',
 'Grecia',
 'Nord',
 'Sardegna',
 'Sicilia',
 'Slovenia',
 'Sud',
 'Svizzera',
 'Slovenia Coupling',
 'Francia Coupling',
 'Austria Coupling',
 'Malta',
 'Montenegro',
 'Grecia Coupling',
 'Italia  Coupling']

In [43]:
from pathlib import Path

output_path = Path('../dataset/clean/prices')

# create folder if non-existent
output_path.mkdir(parents=True, exist_ok=True)

# save in CSV format
prices_data.to_csv(output_path / 'zonal-prices-clean.csv', index=False)