# Data Cleaning and Temporal harmonization

## Load dataset

In [2]:
# import libraries
import pandas as pd
from pathlib import Path
import warnings

# filter User and Filter Warnings for privacy matters
warnings.simplefilter(action="ignore", category=UserWarning)
warnings.simplefilter(action="ignore", category=FutureWarning)

In [3]:
# define initial variables
dataset_path = Path('../dataset/raw/gme/load/')
YEARS = range(2015, 2027)

In [4]:
def parse_italian_number(value):
    # treat nan cells
    if pd.isna(value):
        return float('nan')

    # treat numeric cells
    if isinstance(value, (int, float)):
        return float(value)

    value = str(value).strip()

    if value == '':
        return float('nan')

    # treat Italian numeric format
    value = value.replace('.', '').replace(',', '.')

    return float(value)

In [5]:
# create load dataframe
load_dfs = []

for year in YEARS:
    # load dataframe
    df = pd.read_excel(
            dataset_path / f'GME-load-{year}.xlsx', 
            dtype=str
        )
    
    # immediately convert numeric columns
    load_cols = [
        col for col in df.columns
        if col not in ['Data', 'Ora']
    ]

    df['Ora'] = df['Ora'].astype(int)

    for col in load_cols:
        df[col] = df[col].map(parse_italian_number)

    load_dfs.append(df)

load_data = pd.concat(load_dfs, ignore_index=True)

In [6]:
load_data.shape

(100775, 10)

In [7]:
# check what to clean
load_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Data           100775 non-null  str
 1   Ora            100775 non-null  int64
 2   Centro Nord    100775 non-null  float64
 3   Centro Sud     100775 non-null  float64
 4   Nord           100775 non-null  float64
 5   Sardegna       100775 non-null  float64
 6   Sicilia        100775 non-null  float64
 7   Sud            100775 non-null  float64
 8   Totale Italia  100775 non-null  float64
 9   Calabria       48167 non-null   float64
dtypes: float64(8), int64(1), str(1)
memory usage: 7.7 MB

In [8]:
load_data['Data'].describe()

count         100775
unique          4199
top       25/10/2015
freq              25
Name: Data, dtype: object

In [9]:
load_data['Ora'].describe()

count    100775.000000
mean         12.499995
std           6.922350
min           1.000000
25%           6.500000
50%          12.000000
75%          18.000000
max          25.000000
Name: Ora, dtype: float64

In [10]:
load_data[load_data.columns[2:]].describe()

,Centro Nord,Centro Sud,Nord,Sardegna,Sicilia,Sud,Totale Italia,Calabria
count,100775.000000,100775.000000,100775.000000,100775.000000,100775.000000,100775.000000,100775.000000,48167.000000
mean,3109.175170,5421.629058,18011.154278,973.701498,1910.899743,2442.675735,32172.071988,633.604558
std,784.768814,1128.379916,4216.555105,159.823756,378.591997,650.636840,6716.265355,142.994063
min,1428.476000,2823.343000,8166.990000,568.548000,1073.614000,1210.000000,16272.977000,375.932000
25%,2480.341000,4477.896500,14560.309500,853.308500,1622.381000,1968.635500,26269.936500,524.809000
50%,3062.342000,5451.302000,17347.263000,969.523000,1902.875000,2326.484000,31746.205000,625.072000
75%,3657.856000,6253.596000,21773.218500,1085.962000,2166.696000,2855.301000,37878.179500,724.502500
max,6007.450000,9462.021000,29379.431000,3136.701000,3456.118000,5216.077000,50312.747000,1236.481000

In [11]:
# days with more than 24 hourly periods
daily_periods = (
    load_data
    .groupby('Data')['Ora']
    .agg(['count', 'min', 'max'])
)

daily_periods[daily_periods['count'] != 24]

            count  min  max
Data
25/03/2018     23    1   23
25/10/2015     25    1   25
25/10/2020     25    1   25
26/03/2017     23    1   23
26/03/2023     23    1   23
26/10/2025     25    1   25
27/03/2016     23    1   23
27/03/2022     23    1   23
27/10/2019     25    1   25
27/10/2024     25    1   25
28/03/2021     23    1   23
28/10/2018     25    1   25
29/03/2015     23    1   23
29/03/2020     23    1   23
29/03/2026     23    1   23
29/10/2017     25    1   25
29/10/2023     25    1   25
30/03/2025     23    1   23
30/10/2016     25    1   25
30/10/2022     25    1   25
31/03/2019     23    1   23
31/03/2024     23    1   23
31/10/2021     25    1   25

In [12]:
daily_periods['count'].value_counts().sort_index()

count
23      12
24    4176
25      11
Name: count, dtype: int64

In [13]:
load_data[
    load_data['Data'].isin(
        daily_periods.query('count != 24').index
    )
][['Data', 'Ora', 'Totale Italia']]

             Data  Ora  Totale Italia
2088   29/03/2015    1      24120.304
2089   29/03/2015    2      22191.033
2090   29/03/2015    3      21105.774
2091   29/03/2015    4      21305.470
2092   29/03/2015    5      21346.699
...           ...  ...            ...
98538  29/03/2026   19      31063.300
98539  29/03/2026   20      31372.300
98540  29/03/2026   21      29773.300
98541  29/03/2026   22      27653.000
98542  29/03/2026   23      25310.800

[551 rows x 3 columns]

In [14]:
# 1. convert date
load_data['Data'] = pd.to_datetime(
    load_data['Data'],
    dayfirst=True,
    errors='coerce'
)

# 2. inspect the number of periods per day
daily_periods = (
    load_data
    .groupby('Data')['Ora']
    .agg(['count', 'min', 'max'])
)

print(daily_periods['count'].value_counts().sort_index())

# 3. Inspect non-standard days
print(
    load_data[
        load_data['Data'].isin(
            daily_periods.query('count != 24').index
        )
    ][['Data', 'Ora', 'Totale Italia']]
)

count
23      12
24    4176
25      11
Name: count, dtype: int64
            Data  Ora  Totale Italia
2088  2015-03-29    1      24120.304
2089  2015-03-29    2      22191.033
2090  2015-03-29    3      21105.774
2091  2015-03-29    4      21305.470
2092  2015-03-29    5      21346.699
...          ...  ...            ...
98538 2026-03-29   19      31063.300
98539 2026-03-29   20      31372.300
98540 2026-03-29   21      29773.300
98541 2026-03-29   22      27653.000
98542 2026-03-29   23      25310.800

[551 rows x 3 columns]

In [15]:
# spring DST transition
spring_dates = daily_periods.query('count == 23').index

for date in spring_dates:
    print(f'\n--- {date} ---')
    print(
        load_data.loc[
            load_data['Data'] == date,
            ['Data', 'Ora', 'Totale Italia' ]
        ].to_string(index=False)
    )

--- 2015-03-29 00:00:00 ---
      Data  Ora  Totale Italia
2015-03-29    1      24120.304
2015-03-29    2      22191.033
2015-03-29    3      21105.774
2015-03-29    4      21305.470
2015-03-29    5      21346.699
2015-03-29    6      21569.261
2015-03-29    7      22347.366
2015-03-29    8      24148.307
2015-03-29    9      25622.057
2015-03-29   10      26204.025
2015-03-29   11      25885.065
2015-03-29   12      26025.146
2015-03-29   13      24540.336
2015-03-29   14      23984.348
2015-03-29   15      23559.643
2015-03-29   16      23620.152
2015-03-29   17      25344.926
2015-03-29   18      27923.163
2015-03-29   19      31045.215
2015-03-29   20      31692.215
2015-03-29   21      30179.584
2015-03-29   22      27761.037
2015-03-29   23      25024.539

--- 2016-03-27 00:00:00 ---
      Data  Ora  Totale Italia
2016-03-27    1      22844.756
2016-03-27    2      20825.828
2016-03-27    3      19397.436
2016-03-27    4      19331.908
2016-03-27    5      19414.164
2016-03-27    6      19430.992
2016-03-27    7      19976.209
2016-03-27    8      22036.009
2016-03-27    9      23259.815
2016-03-27   10      23528.815
2016-03-27   11      23939.099
2016-03-27   12      23173.185
2016-03-27   13      21932.771
2016-03-27   14      20741.947
2016-03-27   15      21003.005
2016-03-27   16      21191.021
2016-03-27   17      23019.405
2016-03-27   18      25853.951
2016-03-27   19      28619.290
2016-03-27   20      29354.914
2016-03-27   21      28384.102
2016-03-27   22      26241.077
2016-03-27   23      23304.215

--- 2017-03-26 00:00:00 ---
      Data  Ora  Totale Italia
2017-03-26    1      24647.686
2017-03-26    2      22830.658
2017-03-26    3      21611.531
2017-03-26    4      21372.655
2017-03-26    5      21557.679
2017-03-26    6      21281.981
2017-03-26    7      22064.836
2017-03-26    8      23457.092
2017-03-26    9      25003.809
2017-03-26   10      25986.818
2017-03-26   11      26408.572
2017-03-26   12      26146.717
2017-03-26   13      25312.888
2017-03-26   14      24229.998
2017-03-26   15      24097.718
2017-03-26   16      24365.513
2017-03-26   17      25568.716
2017-03-26   18      28119.904
2017-03-26   19      31265.082
2017-03-26   20      31986.736
2017-03-26   21      30905.103
2017-03-26   22      28945.675
2017-03-26   23      26544.668

--- 2018-03-25 00:00:00 ---
      Data  Ora  Totale Italia
2018-03-25    1      25605.086
2018-03-25    2      23836.438
2018-03-25    3      22443.850
2018-03-25    4      22379.480
2018-03-25    5      22580.616
2018-03-25    6      22610.311
2018-03-25    7      23384.610
2018-03-25    8      25369.592
2018-03-25    9      27047.861
2018-03-25   10      27797.972
2018-03-25   11      28084.274
2018-03-25   12      27868.653
2018-03-25   13      26804.563
2018-03-25   14      26003.171
2018-03-25   15      25916.228
2018-03-25   16      26227.291
2018-03-25   17      27614.220
2018-03-25   18      30193.378
2018-03-25   19      33131.437
2018-03-25   20      33493.152
2018-03-25   21      32039.771
2018-03-25   22      29910.559
2018-03-25   23      27220.868

--- 2019-03-31 00:00:00 ---
      Data  Ora  Totale Italia
2019-03-31    1      24444.914
2019-03-31    2      22753.007
2019-03-31    3      21015.584
2019-03-31    4      21124.513
2019-03-31    5      21407.512
2019-03-31    6      21649.167
2019-03-31    7      22754.588
2019-03-31    8      24239.093
2019-03-31    9      25279.585
2019-03-31   10      25436.207
2019-03-31   11      25382.806
2019-03-31   12      24947.233
2019-03-31   13      23809.323
2019-03-31   14      23337.104
2019-03-31   15      23360.658
2019-03-31   16      23757.730
2019-03-31   17      25180.315
2019-03-31   18      27901.024
2019-03-31   19      30876.427
2019-03-31   20      31698.913
2019-03-31   21      30312.999
2019-03-31   22      28000.600
2019-03-31   23      25081.511

--- 2020-03-29 00:00:00 ---
      Data  Ora  Totale Italia
2020-03-29    1      20128.794
2020-03-29    2      18621.738
2020-03-29    3      17288.063
2020-03-29    4      17210.883
2020-03-29    5      17461.987
2020-03-29    6      17315.717
2020-03-29    7      18118.785
2020-03-29    8      19548.966
2020-03-29    9      20780.177
2020-03-29   10      21155.314
2020-03-29   11      21409.655
2020-03-29   12      21413.172
2020-03-29   13      20399.482
2020-03-29   14      19820.391
2020-03-29   15      19701.400
2020-03-29   16      19703.552
2020-03-29   17      21102.518
2020-03-29   18      23742.717
2020-03-29   19      26627.297
2020-03-29   20      26899.138
2020-03-29   21      25587.528
2020-03-29   22      23561.140
2020-03-29   23      21195.115

--- 2021-03-28 00:00:00 ---
      Data  Ora  Totale Italia
2021-03-28    1      24158.758
2021-03-28    2      22599.031
2021-03-28    3      21449.527
2021-03-28    4      21441.802
2021-03-28    5      21800.804
2021-03-28    6      22125.055
2021-03-28    7      22976.429
2021-03-28    8      24544.621
2021-03-28    9      25752.241
2021-03-28   10      26517.715
2021-03-28   11      26775.249
2021-03-28   12      26757.845
2021-03-28   13      25525.539
2021-03-28   14      24410.437
2021-03-28   15      24087.456
2021-03-28   16      24377.111
2021-03-28   17      26082.919
2021-03-28   18      28636.405
2021-03-28   19      31852.777
2021-03-28   20      31920.768
2021-03-28   21      30166.632
2021-03-28   22      27783.163
2021-03-28   23      25324.112

--- 2022-03-27 00:00:00 ---
      Data  Ora  Totale Italia
2022-03-27    1      23906.783
2022-03-27    2      22771.922
2022-03-27    3      21638.772
2022-03-27    4      21761.328
2022-03-27    5      22109.997
2022-03-27    6      22320.385
2022-03-27    7      23270.440
2022-03-27    8      24800.935
2022-03-27    9      26079.127
2022-03-27   10      26776.637
2022-03-27   11      26875.683
2022-03-27   12      26658.815
2022-03-27   13      25386.604
2022-03-27   14      24426.204
2022-03-27   15      24273.872
2022-03-27   16      24450.285
2022-03-27   17      25567.152
2022-03-27   18      28081.805
2022-03-27   19      31187.018
2022-03-27   20      31433.352
2022-03-27   21      29739.898
2022-03-27   22      27451.658
2022-03-27   23      25099.582

--- 2023-03-26 00:00:00 ---
      Data  Ora  Totale Italia
2023-03-26    1      23209.646
2023-03-26    2      21829.505
2023-03-26    3      20817.598
2023-03-26    4      20700.584
2023-03-26    5      20951.243
2023-03-26    6      21599.599
2023-03-26    7      22457.893
2023-03-26    8      23733.453
2023-03-26    9      25058.135
2023-03-26   10      25580.541
2023-03-26   11      25974.802
2023-03-26   12      26488.219
2023-03-26   13      25260.289
2023-03-26   14      24459.058
2023-03-26   15      24457.130
2023-03-26   16      24309.932
2023-03-26   17      24852.574
2023-03-26   18      26972.670
2023-03-26   19      29605.698
2023-03-26   20      30004.118
2023-03-26   21      28488.643
2023-03-26   22      26294.570
2023-03-26   23      24039.972

--- 2024-03-31 00:00:00 ---
      Data  Ora  Totale Italia
2024-03-31    1      20631.647
2024-03-31    2      19181.185
2024-03-31    3      17992.268
2024-03-31    4      17916.588
2024-03-31    5      18289.717
2024-03-31    6      18463.949
2024-03-31    7      19416.570
2024-03-31    8      20887.066
2024-03-31    9      22211.415
2024-03-31   10      23125.865
2024-03-31   11      23674.916
2024-03-31   12      23604.826
2024-03-31   13      22794.604
2024-03-31   14      21560.751
2024-03-31   15      21134.699
2024-03-31   16      20905.291
2024-03-31   17      21601.044
2024-03-31   18      23387.511
2024-03-31   19      25431.070
2024-03-31   20      26148.988
2024-03-31   21      25207.895
2024-03-31   22      23564.680
2024-03-31   23      21525.893

--- 2025-03-30 00:00:00 ---
      Data  Ora  Totale Italia
2025-03-30    1        23389.3
2025-03-30    2        21994.3
2025-03-30    3        20992.4
2025-03-30    4        20838.7
2025-03-30    5        21134.7
2025-03-30    6        21760.0
2025-03-30    7        22566.4
2025-03-30    8        24041.2
2025-03-30    9        25119.1
2025-03-30   10        26355.1
2025-03-30   11        26535.3
2025-03-30   12        26763.0
2025-03-30   13        25381.4
2025-03-30   14        24281.5
2025-03-30   15        23956.1
2025-03-30   16        24158.3
2025-03-30   17        25154.7
2025-03-30   18        27308.5
2025-03-30   19        29810.5
2025-03-30   20        29875.4
2025-03-30   21        28310.8
2025-03-30   22        26254.3
2025-03-30   23        24079.5

--- 2026-03-29 00:00:00 ---
      Data  Ora  Totale Italia
2026-03-29    1        24248.9
2026-03-29    2        23092.1
2026-03-29    3        21791.2
2026-03-29    4        21919.9
2026-03-29    5        22383.2
2026-03-29    6        23067.9
2026-03-29    7        23997.0
2026-03-29    8        25268.4
2026-03-29    9        26723.0
2026-03-29   10        27528.4
2026-03-29   11        27918.9
2026-03-29   12        28234.7
2026-03-29   13        27450.2
2026-03-29   14        26919.5
2026-03-29   15        26243.3
2026-03-29   16        25496.4
2026-03-29   17        26278.4
2026-03-29   18        28733.8
2026-03-29   19        31063.3
2026-03-29   20        31372.3
2026-03-29   21        29773.3
2026-03-29   22        27653.0
2026-03-29   23        25310.8

In [16]:
# autumn DST transition
autumn_dates = daily_periods.query('count == 25').index

for date in autumn_dates:
    print(f'\n--- {date} ---')
    print(
        load_data.loc[
            load_data['Data'] == date,
            ['Data', 'Ora', 'Totale Italia' ]
        ].to_string(index=False)
    )

--- 2015-10-25 00:00:00 ---
      Data  Ora  Totale Italia
2015-10-25    1      23852.901
2015-10-25    2      22218.764
2015-10-25    3      21386.027
2015-10-25    4      21554.636
2015-10-25    5      20973.890
2015-10-25    6      21014.990
2015-10-25    7      21935.183
2015-10-25    8      22801.795
2015-10-25    9      23609.703
2015-10-25   10      25012.742
2015-10-25   11      25824.848
2015-10-25   12      26884.624
2015-10-25   13      26322.012
2015-10-25   14      25995.502
2015-10-25   15      24602.485
2015-10-25   16      24212.730
2015-10-25   17      24051.622
2015-10-25   18      25087.727
2015-10-25   19      27783.242
2015-10-25   20      30838.048
2015-10-25   21      32384.403
2015-10-25   22      31141.812
2015-10-25   23      29482.083
2015-10-25   24      27372.631
2015-10-25   25      24897.960

--- 2016-10-30 00:00:00 ---
      Data  Ora  Totale Italia
2016-10-30    1      23979.491
2016-10-30    2      22687.338
2016-10-30    3      21430.453
2016-10-30    4      21167.967
2016-10-30    5      20850.743
2016-10-30    6      20804.129
2016-10-30    7      21233.916
2016-10-30    8      22161.735
2016-10-30    9      22767.201
2016-10-30   10      24095.468
2016-10-30   11      25280.249
2016-10-30   12      25705.485
2016-10-30   13      25762.377
2016-10-30   14      25514.666
2016-10-30   15      24148.755
2016-10-30   16      23832.227
2016-10-30   17      24059.064
2016-10-30   18      25226.016
2016-10-30   19      27258.093
2016-10-30   20      30375.599
2016-10-30   21      31585.261
2016-10-30   22      30636.005
2016-10-30   23      29052.553
2016-10-30   24      26956.904
2016-10-30   25      24082.296

--- 2017-10-29 00:00:00 ---
      Data  Ora  Totale Italia
2017-10-29    1      23682.163
2017-10-29    2      22365.631
2017-10-29    3      21227.135
2017-10-29    4      21080.683
2017-10-29    5      20830.514
2017-10-29    6      20775.476
2017-10-29    7      21290.581
2017-10-29    8      22337.311
2017-10-29    9      23688.923
2017-10-29   10      24688.004
2017-10-29   11      25299.222
2017-10-29   12      25614.285
2017-10-29   13      25642.541
2017-10-29   14      25306.478
2017-10-29   15      24084.475
2017-10-29   16      23723.289
2017-10-29   17      24280.129
2017-10-29   18      25235.986
2017-10-29   19      26887.703
2017-10-29   20      29402.085
2017-10-29   21      31126.436
2017-10-29   22      30372.965
2017-10-29   23      28803.317
2017-10-29   24      26692.791
2017-10-29   25      24236.930

--- 2018-10-28 00:00:00 ---
      Data  Ora  Totale Italia
2018-10-28    1      24764.527
2018-10-28    2      23440.056
2018-10-28    3      22454.346
2018-10-28    4      22336.704
2018-10-28    5      22013.346
2018-10-28    6      21921.791
2018-10-28    7      22294.316
2018-10-28    8      23300.849
2018-10-28    9      24602.072
2018-10-28   10      25931.408
2018-10-28   11      26854.840
2018-10-28   12      27523.003
2018-10-28   13      27755.372
2018-10-28   14      27704.074
2018-10-28   15      26356.766
2018-10-28   16      25983.714
2018-10-28   17      26280.769
2018-10-28   18      26905.572
2018-10-28   19      27786.517
2018-10-28   20      30082.379
2018-10-28   21      32094.602
2018-10-28   22      31382.120
2018-10-28   23      29630.227
2018-10-28   24      27555.952
2018-10-28   25      24863.313

--- 2019-10-27 00:00:00 ---
      Data  Ora  Totale Italia
2019-10-27    1      24151.441
2019-10-27    2      22739.865
2019-10-27    3      21993.391
2019-10-27    4      21819.644
2019-10-27    5      21364.215
2019-10-27    6      21345.432
2019-10-27    7      21756.328
2019-10-27    8      22728.630
2019-10-27    9      23550.304
2019-10-27   10      24748.307
2019-10-27   11      25745.578
2019-10-27   12      26115.228
2019-10-27   13      26166.575
2019-10-27   14      25807.337
2019-10-27   15      24726.815
2019-10-27   16      24458.817
2019-10-27   17      24789.742
2019-10-27   18      25872.319
2019-10-27   19      27286.002
2019-10-27   20      29893.589
2019-10-27   21      31365.099
2019-10-27   22      30465.512
2019-10-27   23      28720.536
2019-10-27   24      26767.521
2019-10-27   25      24085.912

--- 2020-10-25 00:00:00 ---
      Data  Ora  Totale Italia
2020-10-25    1      23332.281
2020-10-25    2      22049.568
2020-10-25    3      21243.409
2020-10-25    4      21006.399
2020-10-25    5      20520.413
2020-10-25    6      20429.175
2020-10-25    7      20965.824
2020-10-25    8      21990.406
2020-10-25    9      23073.990
2020-10-25   10      24114.955
2020-10-25   11      25062.660
2020-10-25   12      25509.512
2020-10-25   13      25682.898
2020-10-25   14      25292.036
2020-10-25   15      24161.732
2020-10-25   16      23749.129
2020-10-25   17      24129.858
2020-10-25   18      25165.734
2020-10-25   19      27077.262
2020-10-25   20      29361.283
2020-10-25   21      30553.191
2020-10-25   22      29868.007
2020-10-25   23      27958.281
2020-10-25   24      25880.711
2020-10-25   25      23444.608

--- 2021-10-31 00:00:00 ---
      Data  Ora  Totale Italia
2021-10-31    1      23907.390
2021-10-31    2      22484.584
2021-10-31    3      21608.998
2021-10-31    4      21448.131
2021-10-31    5      21087.527
2021-10-31    6      21089.811
2021-10-31    7      21572.974
2021-10-31    8      22814.317
2021-10-31    9      23810.478
2021-10-31   10      25078.954
2021-10-31   11      26323.415
2021-10-31   12      27090.577
2021-10-31   13      27589.845
2021-10-31   14      27487.908
2021-10-31   15      26286.857
2021-10-31   16      25747.885
2021-10-31   17      25915.209
2021-10-31   18      26504.396
2021-10-31   19      28165.849
2021-10-31   20      30656.198
2021-10-31   21      31892.949
2021-10-31   22      30433.821
2021-10-31   23      28560.193
2021-10-31   24      26355.900
2021-10-31   25      24290.345

--- 2022-10-30 00:00:00 ---
      Data  Ora  Totale Italia
2022-10-30    1      22586.946
2022-10-30    2      21352.559
2022-10-30    3      20657.931
2022-10-30    4      20429.130
2022-10-30    5      20199.256
2022-10-30    6      20137.542
2022-10-30    7      20484.267
2022-10-30    8      21149.506
2022-10-30    9      21993.494
2022-10-30   10      23092.530
2022-10-30   11      24059.313
2022-10-30   12      24531.944
2022-10-30   13      24719.476
2022-10-30   14      24403.377
2022-10-30   15      23459.072
2022-10-30   16      23050.148
2022-10-30   17      23435.902
2022-10-30   18      24256.534
2022-10-30   19      26099.023
2022-10-30   20      28303.574
2022-10-30   21      29413.911
2022-10-30   22      28288.314
2022-10-30   23      26673.049
2022-10-30   24      24755.509
2022-10-30   25      22464.382

--- 2023-10-29 00:00:00 ---
      Data  Ora  Totale Italia
2023-10-29    1      23131.669
2023-10-29    2      21905.346
2023-10-29    3      21206.866
2023-10-29    4      20951.355
2023-10-29    5      20728.944
2023-10-29    6      20628.307
2023-10-29    7      20987.256
2023-10-29    8      21954.441
2023-10-29    9      22831.282
2023-10-29   10      24237.954
2023-10-29   11      25106.050
2023-10-29   12      25523.744
2023-10-29   13      25768.399
2023-10-29   14      25546.185
2023-10-29   15      24724.414
2023-10-29   16      24120.749
2023-10-29   17      24183.991
2023-10-29   18      25099.546
2023-10-29   19      26387.444
2023-10-29   20      28456.396
2023-10-29   21      29678.501
2023-10-29   22      28620.468
2023-10-29   23      26850.304
2023-10-29   24      24991.002
2023-10-29   25      22645.517

--- 2024-10-27 00:00:00 ---
      Data  Ora  Totale Italia
2024-10-27    1      23066.873
2024-10-27    2      21856.813
2024-10-27    3      21024.040
2024-10-27    4      20825.582
2024-10-27    5      20524.413
2024-10-27    6      20525.069
2024-10-27    7      20994.950
2024-10-27    8      22003.768
2024-10-27    9      23014.750
2024-10-27   10      24248.830
2024-10-27   11      25577.550
2024-10-27   12      26141.775
2024-10-27   13      26559.505
2024-10-27   14      26747.614
2024-10-27   15      25671.842
2024-10-27   16      24807.211
2024-10-27   17      24663.851
2024-10-27   18      25335.322
2024-10-27   19      26953.854
2024-10-27   20      29086.532
2024-10-27   21      30372.045
2024-10-27   22      28964.776
2024-10-27   23      27410.181
2024-10-27   24      25671.921
2024-10-27   25      23495.107

--- 2025-10-26 00:00:00 ---
      Data  Ora  Totale Italia
2025-10-26    1        23704.2
2025-10-26    2        22381.7
2025-10-26    3        21793.6
2025-10-26    4        21448.8
2025-10-26    5        21400.7
2025-10-26    6        21337.1
2025-10-26    7        21825.5
2025-10-26    8        22782.8
2025-10-26    9        23282.9
2025-10-26   10        24321.4
2025-10-26   11        25706.0
2025-10-26   12        25963.4
2025-10-26   13        26272.4
2025-10-26   14        26516.2
2025-10-26   15        25495.7
2025-10-26   16        24860.3
2025-10-26   17        25033.4
2025-10-26   18        25962.9
2025-10-26   19        27422.3
2025-10-26   20        29734.1
2025-10-26   21        30955.7
2025-10-26   22        29671.6
2025-10-26   23        28085.7
2025-10-26   24        26261.3
2025-10-26   25        24101.0

In [17]:
load_data['datetime'] = (
    load_data['Data']
    + pd.to_timedelta(load_data['Ora'] - 1, unit='h')
)

diffs = load_data['datetime'].diff()

diffs.value_counts().sort_index()

datetime
0 days 00:00:00        11
0 days 01:00:00    100751
0 days 02:00:00        12
Name: count, dtype: int64

Source for period meaning for GME: https://gme.mercatoelettrico.org/Portals/0/Documents/it-IT/20250101DTF01rev3MPE.pdf

In [18]:
# make a copy
load_data = load_data.copy()

# convert Date
load_data['Date'] = pd.to_datetime(
    load_data['Data'],
    dayfirst=True,
    errors='coerce'
)

# make sure Ora is numeric
load_data['Ora'] = pd.to_numeric(
    load_data['Ora'],
    errors='coerce'
)

In [19]:
periods_per_day = (
    load_data
    .groupby('Date')['Ora']
    .transform('count')
)

load_data['periods_per_day'] = periods_per_day

In [ ]:
def gme_local_datetime(row):
    date = row['Date']
    hour = row['Ora']
    periods = row['periods_per_day']

    # normal day: 24 periods
    if periods == 24:
        return date + pd.to_timedelta(hour - 1, unit='h')

    # spring DST: 23 periods
    # Hr 1 = 00:00
    # Hr 2 = 01:00
    # Hr 3 = 03:00
    elif periods == 23:
        if hour >= 3:
            return date + pd.to_timedelta(hour, unit='h')
        else:
            return date + pd.to_timedelta(hour - 1, unit='h')

    # Autumn DST: 25 periods
    # Hr 1 = 00:00
    # Hr 2 = 01:00
    # Hr 3 = 02:00 CEST
    # Hr 4 = 02:00 CET
    # Hr 5 = 03:00 CET
    elif periods == 25:
        if hour <= 2:
            return date + pd.to_timedelta(hour - 1, unit='h')
        elif hour <= 4:
            return date + pd.Timedelta(hours=2)
        else:
            return date + pd.to_timedelta(hour - 2, unit='h')

    else:
        raise ValueError(
            f"Unexpected number of periods ({periods}) for {date}"
        )

In [21]:
load_data['datetime_local_naive'] = load_data.apply(
    gme_local_datetime,
    axis=1
)

In [22]:
ambiguous = (
    (load_data['periods_per_day'] == 25)
    & (load_data['Ora'] == 3)
)

load_data['datetime_local'] = (
    load_data['datetime_local_naive']
    .dt.tz_localize(
        'Europe/Rome',
        ambiguous=ambiguous,
        nonexistent='raise'
    )
)

In [23]:
load_data['datetime_UTC'] = (
    load_data['datetime_local']
    .dt.tz_convert('UTC')
)

In [24]:
load_data.head()

,Data,Ora,Centro Nord,Centro Sud,Nord,Sardegna,Sicilia,Sud,Totale Italia,Calabria,datetime,Date,periods_per_day,datetime_local_naive,datetime_local,datetime_UTC
0,2015-01-01,1,2670.851,4590.186,10774.037,997.138,1930.829,2347.270,23310.311,NaN,2015-01-01 00:00:00,2015-01-01,24,2015-01-01 00:00:00,2015-01-01 00:00:00+01:00,2014-12-31 23:00:00+00:00
1,2015-01-01,2,2513.713,4342.739,10576.993,951.110,1821.231,2213.368,22419.154,NaN,2015-01-01 01:00:00,2015-01-01,24,2015-01-01 01:00:00,2015-01-01 01:00:00+01:00,2015-01-01 00:00:00+00:00
2,2015-01-01,3,2392.789,4028.419,10169.339,903.001,1769.136,2031.384,21294.068,NaN,2015-01-01 02:00:00,2015-01-01,24,2015-01-01 02:00:00,2015-01-01 02:00:00+01:00,2015-01-01 01:00:00+00:00
3,2015-01-01,4,2259.362,3732.403,9769.460,855.196,1673.111,1869.842,20159.374,NaN,2015-01-01 03:00:00,2015-01-01,24,2015-01-01 03:00:00,2015-01-01 03:00:00+01:00,2015-01-01 02:00:00+00:00
4,2015-01-01,5,2245.990,3363.157,9613.212,855.747,1536.739,1761.414,19376.259,NaN,2015-01-01 04:00:00,2015-01-01,24,2015-01-01 04:00:00,2015-01-01 04:00:00+01:00,2015-01-01 03:00:00+00:00

In [25]:
load_data.loc[
    load_data['Date'] == '2015-10-25',
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'      Date  Ora            datetime_local              datetime_UTC\n2015-10-25    1 2015-10-25 00:00:00+02:00 2015-10-24 22:00:00+00:00\n2015-10-25    2 2015-10-25 01:00:00+02:00 2015-10-24 23:00:00+00:00\n2015-10-25    3 2015-10-25 02:00:00+02:00 2015-10-25 00:00:00+00:00\n2015-10-25    4 2015-10-25 02:00:00+01:00 2015-10-25 01:00:00+00:00\n2015-10-25    5 2015-10-25 03:00:00+01:00 2015-10-25 02:00:00+00:00\n2015-10-25    6 2015-10-25 04:00:00+01:00 2015-10-25 03:00:00+00:00\n2015-10-25    7 2015-10-25 05:00:00+01:00 2015-10-25 04:00:00+00:00\n2015-10-25    8 2015-10-25 06:00:00+01:00 2015-10-25 05:00:00+00:00\n2015-10-25    9 2015-10-25 07:00:00+01:00 2015-10-25 06:00:00+00:00\n2015-10-25   10 2015-10-25 08:00:00+01:00 2015-10-25 07:00:00+00:00\n2015-10-25   11 2015-10-25 09:00:00+01:00 2015-10-25 08:00:00+00:00\n2015-10-25   12 2015-10-25 10:00:00+01:00 2015-10-25 09:00:00+00:00\n2015-10-25   13 2015-10-25 11:00:00+01:00 2015-10-25 10:00:00+00:00\n2015-10-25   14 2015-10-25 12:00:00+01:00 2015-10-25 11:00:00+00:00\n2015-10-25   15 2015-10-25 13:00:00+01:00 2015-10-25 12:00:00+00:00\n2015-10-25   16 2015-10-25 14:00:00+01:00 2015-10-25 13:00:00+00:00\n2015-10-25   17 2015-10-25 15:00:00+01:00 2015-10-25 14:00:00+00:00\n2015-10-25   18 2015-10-25 16:00:00+01:00 2015-10-25 15:00:00+00:00\n2015-10-25   19 2015-10-25 17:00:00+01:00 2015-10-25 16:00:00+00:00\n2015-10-25   20 2015-10-25 18:00:00+01:00 2015-10-25 17:00:00+00:00\n2015-10-25   21 2015-10-25 19:00:00+01:00 2015-10-25 18:00:00+00:00\n2015-10-25   22 2015-10-25 20:00:00+01:00 2015-10-25 19:00:00+00:00\n2015-10-25   23 2015-10-25 21:00:00+01:00 2015-10-25 20:00:00+00:00\n2015-10-25   24 2015-10-25 22:00:00+01:00 2015-10-25 21:00:00+00:00\n2015-10-25   25 2015-10-25 23:00:00+01:00 2015-10-25 22:00:00+00:00'

In [26]:
load_data['datetime_UTC'].diff().value_counts().head()

datetime_UTC
0 days 01:00:00    100774
Name: count, dtype: int64

In [27]:
load_data.loc[
    load_data['Date'].isin([
        '2015-03-29',
        '2015-10-25',
        '2015-10-26'
    ]),
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'Empty DataFrame\nColumns: [Date, Ora, datetime_local, datetime_UTC]\nIndex: []'

In [28]:
print(
    load_data['datetime_UTC'].isna().sum()
)

0

In [29]:
load_data = load_data.drop(
    columns=['periods_per_day', 'datetime_local_naive']
)

In [30]:
load_data = load_data[
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
    + [
        col for col in load_data.columns
        if col not in [
            'Date',
            'Ora',
            'datetime_local',
            'datetime_UTC'
        ]
    ]
]

In [31]:
load_data[
    load_data['Date'].dt.strftime('%Y-%m-%d') == '2015-03-29'
][['Date', 'Ora', 'datetime_local', 'datetime_UTC']]

           Date  Ora            datetime_local              datetime_UTC
2088 2015-03-29    1 2015-03-29 00:00:00+01:00 2015-03-28 23:00:00+00:00
2089 2015-03-29    2 2015-03-29 01:00:00+01:00 2015-03-29 00:00:00+00:00
2090 2015-03-29    3 2015-03-29 03:00:00+02:00 2015-03-29 01:00:00+00:00
2091 2015-03-29    4 2015-03-29 04:00:00+02:00 2015-03-29 02:00:00+00:00
2092 2015-03-29    5 2015-03-29 05:00:00+02:00 2015-03-29 03:00:00+00:00
2093 2015-03-29    6 2015-03-29 06:00:00+02:00 2015-03-29 04:00:00+00:00
2094 2015-03-29    7 2015-03-29 07:00:00+02:00 2015-03-29 05:00:00+00:00
2095 2015-03-29    8 2015-03-29 08:00:00+02:00 2015-03-29 06:00:00+00:00
2096 2015-03-29    9 2015-03-29 09:00:00+02:00 2015-03-29 07:00:00+00:00
2097 2015-03-29   10 2015-03-29 10:00:00+02:00 2015-03-29 08:00:00+00:00
2098 2015-03-29   11 2015-03-29 11:00:00+02:00 2015-03-29 09:00:00+00:00
2099 2015-03-29   12 2015-03-29 12:00:00+02:00 2015-03-29 10:00:00+00:00
2100 2015-03-29   13 2015-03-29 13:00:00+02:00 2015-03-29 11:00:00+00:00
2101 2015-03-29   14 2015-03-29 14:00:00+02:00 2015-03-29 12:00:00+00:00
2102 2015-03-29   15 2015-03-29 15:00:00+02:00 2015-03-29 13:00:00+00:00
2103 2015-03-29   16 2015-03-29 16:00:00+02:00 2015-03-29 14:00:00+00:00
2104 2015-03-29   17 2015-03-29 17:00:00+02:00 2015-03-29 15:00:00+00:00
2105 2015-03-29   18 2015-03-29 18:00:00+02:00 2015-03-29 16:00:00+00:00
2106 2015-03-29   19 2015-03-29 19:00:00+02:00 2015-03-29 17:00:00+00:00
2107 2015-03-29   20 2015-03-29 20:00:00+02:00 2015-03-29 18:00:00+00:00
2108 2015-03-29   21 2015-03-29 21:00:00+02:00 2015-03-29 19:00:00+00:00
2109 2015-03-29   22 2015-03-29 22:00:00+02:00 2015-03-29 20:00:00+00:00
2110 2015-03-29   23 2015-03-29 23:00:00+02:00 2015-03-29 21:00:00+00:00

In [32]:
load_data.loc[
    load_data['Date'].dt.strftime('%Y-%m-%d') == '2015-03-29',
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'      Date  Ora            datetime_local              datetime_UTC\n2015-03-29    1 2015-03-29 00:00:00+01:00 2015-03-28 23:00:00+00:00\n2015-03-29    2 2015-03-29 01:00:00+01:00 2015-03-29 00:00:00+00:00\n2015-03-29    3 2015-03-29 03:00:00+02:00 2015-03-29 01:00:00+00:00\n2015-03-29    4 2015-03-29 04:00:00+02:00 2015-03-29 02:00:00+00:00\n2015-03-29    5 2015-03-29 05:00:00+02:00 2015-03-29 03:00:00+00:00\n2015-03-29    6 2015-03-29 06:00:00+02:00 2015-03-29 04:00:00+00:00\n2015-03-29    7 2015-03-29 07:00:00+02:00 2015-03-29 05:00:00+00:00\n2015-03-29    8 2015-03-29 08:00:00+02:00 2015-03-29 06:00:00+00:00\n2015-03-29    9 2015-03-29 09:00:00+02:00 2015-03-29 07:00:00+00:00\n2015-03-29   10 2015-03-29 10:00:00+02:00 2015-03-29 08:00:00+00:00\n2015-03-29   11 2015-03-29 11:00:00+02:00 2015-03-29 09:00:00+00:00\n2015-03-29   12 2015-03-29 12:00:00+02:00 2015-03-29 10:00:00+00:00\n2015-03-29   13 2015-03-29 13:00:00+02:00 2015-03-29 11:00:00+00:00\n2015-03-29   14 2015-03-29 14:00:00+02:00 2015-03-29 12:00:00+00:00\n2015-03-29   15 2015-03-29 15:00:00+02:00 2015-03-29 13:00:00+00:00\n2015-03-29   16 2015-03-29 16:00:00+02:00 2015-03-29 14:00:00+00:00\n2015-03-29   17 2015-03-29 17:00:00+02:00 2015-03-29 15:00:00+00:00\n2015-03-29   18 2015-03-29 18:00:00+02:00 2015-03-29 16:00:00+00:00\n2015-03-29   19 2015-03-29 19:00:00+02:00 2015-03-29 17:00:00+00:00\n2015-03-29   20 2015-03-29 20:00:00+02:00 2015-03-29 18:00:00+00:00\n2015-03-29   21 2015-03-29 21:00:00+02:00 2015-03-29 19:00:00+00:00\n2015-03-29   22 2015-03-29 22:00:00+02:00 2015-03-29 20:00:00+00:00\n2015-03-29   23 2015-03-29 23:00:00+02:00 2015-03-29 21:00:00+00:00'

In [33]:
load_data.columns

Index(['Date', 'Ora', 'datetime_local', 'datetime_UTC', 'Data', 'Centro Nord',
       'Centro Sud', 'Nord', 'Sardegna', 'Sicilia', 'Sud', 'Totale Italia',
       'Calabria', 'datetime'],
      dtype='str')

In [34]:
load_data = load_data.drop(
    columns=['Data', 'datetime']
)

In [35]:
# final cleaning check
load_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            100775 non-null  datetime64[us]
 1   Ora             100775 non-null  int64
 2   datetime_local  100775 non-null  datetime64[us, Europe/Rome]
 3   datetime_UTC    100775 non-null  datetime64[us, UTC]
 4   Centro Nord     100775 non-null  float64
 5   Centro Sud      100775 non-null  float64
 6   Nord            100775 non-null  float64
 7   Sardegna        100775 non-null  float64
 8   Sicilia         100775 non-null  float64
 9   Sud             100775 non-null  float64
 10  Totale Italia   100775 non-null  float64
 11  Calabria        48167 non-null   float64
dtypes: datetime64[us, Europe/Rome](1), datetime64[us, UTC](1), datetime64[us](1), float64(8), int64(1)
memory usage: 9.2 MB

In [36]:
loads = load_data.columns[4:]

for col in loads:
    print(f"\n--- {col} ---")
    print("Dtype:", load_data[col].dtype)
    print("Tipi Python:")
    print(load_data[col].map(type).value_counts())

    print("Primi valori:")
    print(load_data[col].head(10).map(repr).tolist())

--- Centro Nord ---
Dtype: float64
Tipi Python:
Centro Nord
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['2670.851', '2513.713', '2392.789', '2259.362', '2245.99', '2230.202', '2465.643', '2474.337', '2378.542', '2480.273']

--- Centro Sud ---
Dtype: float64
Tipi Python:
Centro Sud
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['4590.186', '4342.739', '4028.419', '3732.403', '3363.157', '3318.785', '3601.506', '3822.726', '3947.336', '4246.754']

--- Nord ---
Dtype: float64
Tipi Python:
Nord
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['10774.037', '10576.993', '10169.339', '9769.46', '9613.212', '9853.684', '10232.05', '10636.872', '10603.542', '10957.935']

--- Sardegna ---
Dtype: float64
Tipi Python:
Sardegna
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['997.138', '951.11', '903.001', '855.196', '855.747', '834.056', '880.573', '912.138', '955.412', '1024.877']

--- Sicilia ---
Dtype: float64
Tipi Python:
Sicilia
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['1930.829', '1821.231', '1769.136', '1673.111', '1536.739', '1537.46', '1512.556', '1485.03', '1529.439', '1725.426']

--- Sud ---
Dtype: float64
Tipi Python:
Sud
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['2347.27', '2213.368', '2031.384', '1869.842', '1761.414', '1731.533', '1846.194', '1844.356', '1988.343', '2177.488']

--- Totale Italia ---
Dtype: float64
Tipi Python:
Totale Italia
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['23310.311', '22419.154', '21294.068', '20159.374', '19376.259', '19505.72', '20538.522', '21175.459', '21402.614', '22612.753']

--- Calabria ---
Dtype: float64
Tipi Python:
Calabria
<class 'float'>    100775
Name: count, dtype: int64
Primi valori:
['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan']

In [37]:
load_data['Sardegna']

0          997.138
1          951.110
2          903.001
3          855.196
4          855.747
            ...
100770    1422.800
100771    1450.400
100772    1419.200
100773    1346.600
100774    1250.500
Name: Sardegna, Length: 100775, dtype: float64

In [38]:
load_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            100775 non-null  datetime64[us]
 1   Ora             100775 non-null  int64
 2   datetime_local  100775 non-null  datetime64[us, Europe/Rome]
 3   datetime_UTC    100775 non-null  datetime64[us, UTC]
 4   Centro Nord     100775 non-null  float64
 5   Centro Sud      100775 non-null  float64
 6   Nord            100775 non-null  float64
 7   Sardegna        100775 non-null  float64
 8   Sicilia         100775 non-null  float64
 9   Sud             100775 non-null  float64
 10  Totale Italia   100775 non-null  float64
 11  Calabria        48167 non-null   float64
dtypes: datetime64[us, Europe/Rome](1), datetime64[us, UTC](1), datetime64[us](1), float64(8), int64(1)
memory usage: 9.2 MB

In [39]:
load_data.columns.tolist()

['Date',
 'Ora',
 'datetime_local',
 'datetime_UTC',
 'Centro Nord',
 'Centro Sud',
 'Nord',
 'Sardegna',
 'Sicilia',
 'Sud',
 'Totale Italia',
 'Calabria']

In [40]:
load_data

,Date,Ora,datetime_local,datetime_UTC,Centro Nord,Centro Sud,Nord,Sardegna,Sicilia,Sud,Totale Italia,Calabria
0,2015-01-01,1,2015-01-01 00:00:00+01:00,2014-12-31 23:00:00+00:00,2670.851,4590.186,10774.037,997.138,1930.829,2347.270,23310.311,NaN
1,2015-01-01,2,2015-01-01 01:00:00+01:00,2015-01-01 00:00:00+00:00,2513.713,4342.739,10576.993,951.110,1821.231,2213.368,22419.154,NaN
2,2015-01-01,3,2015-01-01 02:00:00+01:00,2015-01-01 01:00:00+00:00,2392.789,4028.419,10169.339,903.001,1769.136,2031.384,21294.068,NaN
3,2015-01-01,4,2015-01-01 03:00:00+01:00,2015-01-01 02:00:00+00:00,2259.362,3732.403,9769.460,855.196,1673.111,1869.842,20159.374,NaN
4,2015-01-01,5,2015-01-01 04:00:00+01:00,2015-01-01 03:00:00+00:00,2245.990,3363.157,9613.212,855.747,1536.739,1761.414,19376.259,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
100770,2026-06-30,20,2026-06-30 19:00:00+02:00,2026-06-30 17:00:00+00:00,4370.900,8561.800,27660.000,1422.800,2603.700,2926.700,48437.300,891.5
100771,2026-06-30,21,2026-06-30 20:00:00+02:00,2026-06-30 18:00:00+00:00,4242.000,8454.600,26765.100,1450.400,2641.600,2921.000,47383.500,908.9
100772,2026-06-30,22,2026-06-30 21:00:00+02:00,2026-06-30 19:00:00+00:00,4090.800,8224.800,25945.600,1419.200,2566.300,2825.600,45951.100,878.8
100773,2026-06-30,23,2026-06-30 22:00:00+02:00,2026-06-30 20:00:00+00:00,3776.100,7714.400,24390.600,1346.600,2412.600,2743.600,43204.200,820.4
100774,2026-06-30,24,2026-06-30 23:00:00+02:00,2026-06-30 21:00:00+00:00,3427.600,7155.800,22678.600,1250.500,2261.400,2585.600,40098.300,738.9

In [ ]:
from pathlib import Path

output_path = Path('../dataset/clean/load')

# create folder if non-existent
output_path.mkdir(parents=True, exist_ok=True)

# save in CSV format
load_data.to_csv(output_path / 'load-clean.csv', index=False)