# Data Cleaning and Temporal harmonization

## Load dataset

In [1]:
# import libraries
import pandas as pd
from pathlib import Path
import warnings

# filter User and Filter Warnings for privacy matters
warnings.simplefilter(action="ignore", category=UserWarning)
warnings.simplefilter(action="ignore", category=FutureWarning)

In [5]:
# define initial variables
dataset_path = Path('../dataset/raw/gme/load/')
YEARS = range(2015, 2027)

# create prices dataframe
load_dfs = [
    pd.read_excel(
        dataset_path / f'GME-load-{year}.xlsx', 
        decimal=','
    )
    for year in YEARS
]

load_data = pd.concat(load_dfs, ignore_index=True)

In [6]:
load_data

,Data,Ora,Centro Nord,Centro Sud,Nord,Sardegna,Sicilia,Sud,Totale Italia,Calabria
0,01/01/2015,1,"2.670,851","4.590,186","10.774,037",997.138,"1.930,829","2.347,270","23.310,311",NaN
1,01/01/2015,2,"2.513,713","4.342,739","10.576,993",951.110,"1.821,231","2.213,368","22.419,154",NaN
2,01/01/2015,3,"2.392,789","4.028,419","10.169,339",903.001,"1.769,136","2.031,384","21.294,068",NaN
3,01/01/2015,4,"2.259,362","3.732,403","9.769,460",855.196,"1.673,111","1.869,842","20.159,374",NaN
4,01/01/2015,5,"2.245,990","3.363,157","9.613,212",855.747,"1.536,739","1.761,414","19.376,259",NaN
...,...,...,...,...,...,...,...,...,...,...
100770,30/06/2026,20,"4.370,9","8.561,8","27.660,0","1.422,8","2.603,7","2.926,7","48.437,3",891.5
100771,30/06/2026,21,"4.242,0","8.454,6","26.765,1","1.450,4","2.641,6","2.921,0","47.383,5",908.9
100772,30/06/2026,22,"4.090,8","8.224,8","25.945,6","1.419,2","2.566,3","2.825,6","45.951,1",878.8
100773,30/06/2026,23,"3.776,1","7.714,4","24.390,6","1.346,6","2.412,6","2.743,6","43.204,2",820.4
100774,30/06/2026,24,"3.427,6","7.155,8","22.678,6","1.250,5","2.261,4","2.585,6","40.098,3",738.9

In [7]:
load_data.shape

(100775, 10)

In [8]:
# check what to clean
load_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Data           100775 non-null  str
 1   Ora            100775 non-null  int64
 2   Centro Nord    100775 non-null  str
 3   Centro Sud     100775 non-null  str
 4   Nord           100775 non-null  str
 5   Sardegna       100775 non-null  str
 6   Sicilia        100775 non-null  str
 7   Sud            100775 non-null  str
 8   Totale Italia  100775 non-null  str
 9   Calabria       48167 non-null   object
dtypes: int64(1), object(1), str(8)
memory usage: 7.7+ MB

In [9]:
load_data['Data'].describe()

count         100775
unique          4199
top       25/10/2015
freq              25
Name: Data, dtype: object

In [10]:
load_data['Ora'].describe()

count    100775.000000
mean         12.499995
std           6.922350
min           1.000000
25%           6.500000
50%          12.000000
75%          18.000000
max          25.000000
Name: Ora, dtype: float64

In [11]:
load_data[load_data.columns[2:]].describe()

,Centro Nord,Centro Sud,Nord,Sardegna,Sicilia,Sud,Totale Italia,Calabria
count,100775,100775,100775,100775,100775,100775,100775,48167
unique,96252,98012,99888,86668,93029,94112,100249,40696
top,"2.591,7","5.359,6","15.965,0",885.2,"1.780,8","1.570,2","30.693,9",576.8
freq,5,5,3,12,8,7,3,10

In [12]:
# days with more than 24 hourly periods
daily_periods = (
    load_data
    .groupby('Data')['Ora']
    .agg(['count', 'min', 'max'])
)

daily_periods[daily_periods['count'] != 24]

            count  min  max
Data
25/03/2018     23    1   23
25/10/2015     25    1   25
25/10/2020     25    1   25
26/03/2017     23    1   23
26/03/2023     23    1   23
26/10/2025     25    1   25
27/03/2016     23    1   23
27/03/2022     23    1   23
27/10/2019     25    1   25
27/10/2024     25    1   25
28/03/2021     23    1   23
28/10/2018     25    1   25
29/03/2015     23    1   23
29/03/2020     23    1   23
29/03/2026     23    1   23
29/10/2017     25    1   25
29/10/2023     25    1   25
30/03/2025     23    1   23
30/10/2016     25    1   25
30/10/2022     25    1   25
31/03/2019     23    1   23
31/03/2024     23    1   23
31/10/2021     25    1   25

In [13]:
daily_periods['count'].value_counts().sort_index()

count
23      12
24    4176
25      11
Name: count, dtype: int64

In [15]:
load_data[
    load_data['Data'].isin(
        daily_periods.query('count != 24').index
    )
][['Data', 'Ora', 'Totale Italia']]

             Data  Ora Totale Italia
2088   29/03/2015    1    24.120,304
2089   29/03/2015    2    22.191,033
2090   29/03/2015    3    21.105,774
2091   29/03/2015    4    21.305,470
2092   29/03/2015    5    21.346,699
...           ...  ...           ...
98538  29/03/2026   19      31.063,3
98539  29/03/2026   20      31.372,3
98540  29/03/2026   21      29.773,3
98541  29/03/2026   22      27.653,0
98542  29/03/2026   23      25.310,8

[551 rows x 3 columns]

In [17]:
# 1. convert date
load_data['Data'] = pd.to_datetime(
    load_data['Data'],
    dayfirst=True,
    errors='coerce'
)

# 2. inspect the number of periods per day
daily_periods = (
    load_data
    .groupby('Data')['Ora']
    .agg(['count', 'min', 'max'])
)

print(daily_periods['count'].value_counts().sort_index())

# 3. Inspect non-standard days
print(
    load_data[
        load_data['Data'].isin(
            daily_periods.query('count != 24').index
        )
    ][['Data', 'Ora', 'Totale Italia']]
)

count
23      12
24    4176
25      11
Name: count, dtype: int64
            Data  Ora Totale Italia
2088  2015-03-29    1    24.120,304
2089  2015-03-29    2    22.191,033
2090  2015-03-29    3    21.105,774
2091  2015-03-29    4    21.305,470
2092  2015-03-29    5    21.346,699
...          ...  ...           ...
98538 2026-03-29   19      31.063,3
98539 2026-03-29   20      31.372,3
98540 2026-03-29   21      29.773,3
98541 2026-03-29   22      27.653,0
98542 2026-03-29   23      25.310,8

[551 rows x 3 columns]

In [20]:
# spring DST transition
spring_dates = daily_periods.query('count == 23').index

for date in spring_dates:
    print(f'\n--- {date} ---')
    print(
        load_data.loc[
            load_data['Data'] == date,
            ['Data', 'Ora', 'Totale Italia' ]
        ].to_string(index=False)
    )

--- 2015-03-29 00:00:00 ---
      Data  Ora Totale Italia
2015-03-29    1    24.120,304
2015-03-29    2    22.191,033
2015-03-29    3    21.105,774
2015-03-29    4    21.305,470
2015-03-29    5    21.346,699
2015-03-29    6    21.569,261
2015-03-29    7    22.347,366
2015-03-29    8    24.148,307
2015-03-29    9    25.622,057
2015-03-29   10    26.204,025
2015-03-29   11    25.885,065
2015-03-29   12    26.025,146
2015-03-29   13    24.540,336
2015-03-29   14    23.984,348
2015-03-29   15    23.559,643
2015-03-29   16    23.620,152
2015-03-29   17    25.344,926
2015-03-29   18    27.923,163
2015-03-29   19    31.045,215
2015-03-29   20    31.692,215
2015-03-29   21    30.179,584
2015-03-29   22    27.761,037
2015-03-29   23    25.024,539

--- 2016-03-27 00:00:00 ---
      Data  Ora Totale Italia
2016-03-27    1    22.844,756
2016-03-27    2    20.825,828
2016-03-27    3    19.397,436
2016-03-27    4    19.331,908
2016-03-27    5    19.414,164
2016-03-27    6    19.430,992
2016-03-27    7    19.976,209
2016-03-27    8    22.036,009
2016-03-27    9    23.259,815
2016-03-27   10    23.528,815
2016-03-27   11    23.939,099
2016-03-27   12    23.173,185
2016-03-27   13    21.932,771
2016-03-27   14    20.741,947
2016-03-27   15    21.003,005
2016-03-27   16    21.191,021
2016-03-27   17    23.019,405
2016-03-27   18    25.853,951
2016-03-27   19    28.619,290
2016-03-27   20    29.354,914
2016-03-27   21    28.384,102
2016-03-27   22    26.241,077
2016-03-27   23    23.304,215

--- 2017-03-26 00:00:00 ---
      Data  Ora Totale Italia
2017-03-26    1    24.647,686
2017-03-26    2    22.830,658
2017-03-26    3    21.611,531
2017-03-26    4    21.372,655
2017-03-26    5    21.557,679
2017-03-26    6    21.281,981
2017-03-26    7    22.064,836
2017-03-26    8    23.457,092
2017-03-26    9    25.003,809
2017-03-26   10    25.986,818
2017-03-26   11    26.408,572
2017-03-26   12    26.146,717
2017-03-26   13    25.312,888
2017-03-26   14    24.229,998
2017-03-26   15    24.097,718
2017-03-26   16    24.365,513
2017-03-26   17    25.568,716
2017-03-26   18    28.119,904
2017-03-26   19    31.265,082
2017-03-26   20    31.986,736
2017-03-26   21    30.905,103
2017-03-26   22    28.945,675
2017-03-26   23    26.544,668

--- 2018-03-25 00:00:00 ---
      Data  Ora Totale Italia
2018-03-25    1    25.605,086
2018-03-25    2    23.836,438
2018-03-25    3    22.443,850
2018-03-25    4    22.379,480
2018-03-25    5    22.580,616
2018-03-25    6    22.610,311
2018-03-25    7    23.384,610
2018-03-25    8    25.369,592
2018-03-25    9    27.047,861
2018-03-25   10    27.797,972
2018-03-25   11    28.084,274
2018-03-25   12    27.868,653
2018-03-25   13    26.804,563
2018-03-25   14    26.003,171
2018-03-25   15    25.916,228
2018-03-25   16    26.227,291
2018-03-25   17    27.614,220
2018-03-25   18    30.193,378
2018-03-25   19    33.131,437
2018-03-25   20    33.493,152
2018-03-25   21    32.039,771
2018-03-25   22    29.910,559
2018-03-25   23    27.220,868

--- 2019-03-31 00:00:00 ---
      Data  Ora Totale Italia
2019-03-31    1    24.444,914
2019-03-31    2    22.753,007
2019-03-31    3    21.015,584
2019-03-31    4    21.124,513
2019-03-31    5    21.407,512
2019-03-31    6    21.649,167
2019-03-31    7    22.754,588
2019-03-31    8    24.239,093
2019-03-31    9    25.279,585
2019-03-31   10    25.436,207
2019-03-31   11    25.382,806
2019-03-31   12    24.947,233
2019-03-31   13    23.809,323
2019-03-31   14    23.337,104
2019-03-31   15    23.360,658
2019-03-31   16    23.757,730
2019-03-31   17    25.180,315
2019-03-31   18    27.901,024
2019-03-31   19    30.876,427
2019-03-31   20    31.698,913
2019-03-31   21    30.312,999
2019-03-31   22    28.000,600
2019-03-31   23    25.081,511

--- 2020-03-29 00:00:00 ---
      Data  Ora Totale Italia
2020-03-29    1    20.128,794
2020-03-29    2    18.621,738
2020-03-29    3    17.288,063
2020-03-29    4    17.210,883
2020-03-29    5    17.461,987
2020-03-29    6    17.315,717
2020-03-29    7    18.118,785
2020-03-29    8    19.548,966
2020-03-29    9    20.780,177
2020-03-29   10    21.155,314
2020-03-29   11    21.409,655
2020-03-29   12    21.413,172
2020-03-29   13    20.399,482
2020-03-29   14    19.820,391
2020-03-29   15    19.701,400
2020-03-29   16    19.703,552
2020-03-29   17    21.102,518
2020-03-29   18    23.742,717
2020-03-29   19    26.627,297
2020-03-29   20    26.899,138
2020-03-29   21    25.587,528
2020-03-29   22    23.561,140
2020-03-29   23    21.195,115

--- 2021-03-28 00:00:00 ---
      Data  Ora Totale Italia
2021-03-28    1    24.158,758
2021-03-28    2    22.599,031
2021-03-28    3    21.449,527
2021-03-28    4    21.441,802
2021-03-28    5    21.800,804
2021-03-28    6    22.125,055
2021-03-28    7    22.976,429
2021-03-28    8    24.544,621
2021-03-28    9    25.752,241
2021-03-28   10    26.517,715
2021-03-28   11    26.775,249
2021-03-28   12    26.757,845
2021-03-28   13    25.525,539
2021-03-28   14    24.410,437
2021-03-28   15    24.087,456
2021-03-28   16    24.377,111
2021-03-28   17    26.082,919
2021-03-28   18    28.636,405
2021-03-28   19    31.852,777
2021-03-28   20    31.920,768
2021-03-28   21    30.166,632
2021-03-28   22    27.783,163
2021-03-28   23    25.324,112

--- 2022-03-27 00:00:00 ---
      Data  Ora Totale Italia
2022-03-27    1    23.906,783
2022-03-27    2    22.771,922
2022-03-27    3    21.638,772
2022-03-27    4    21.761,328
2022-03-27    5    22.109,997
2022-03-27    6    22.320,385
2022-03-27    7    23.270,440
2022-03-27    8    24.800,935
2022-03-27    9    26.079,127
2022-03-27   10    26.776,637
2022-03-27   11    26.875,683
2022-03-27   12    26.658,815
2022-03-27   13    25.386,604
2022-03-27   14    24.426,204
2022-03-27   15    24.273,872
2022-03-27   16    24.450,285
2022-03-27   17    25.567,152
2022-03-27   18    28.081,805
2022-03-27   19    31.187,018
2022-03-27   20    31.433,352
2022-03-27   21    29.739,898
2022-03-27   22    27.451,658
2022-03-27   23    25.099,582

--- 2023-03-26 00:00:00 ---
      Data  Ora Totale Italia
2023-03-26    1    23.209,646
2023-03-26    2    21.829,505
2023-03-26    3    20.817,598
2023-03-26    4    20.700,584
2023-03-26    5    20.951,243
2023-03-26    6    21.599,599
2023-03-26    7    22.457,893
2023-03-26    8    23.733,453
2023-03-26    9    25.058,135
2023-03-26   10    25.580,541
2023-03-26   11    25.974,802
2023-03-26   12    26.488,219
2023-03-26   13    25.260,289
2023-03-26   14    24.459,058
2023-03-26   15    24.457,130
2023-03-26   16    24.309,932
2023-03-26   17    24.852,574
2023-03-26   18    26.972,670
2023-03-26   19    29.605,698
2023-03-26   20    30.004,118
2023-03-26   21    28.488,643
2023-03-26   22    26.294,570
2023-03-26   23    24.039,972

--- 2024-03-31 00:00:00 ---
      Data  Ora Totale Italia
2024-03-31    1    20.631,647
2024-03-31    2    19.181,185
2024-03-31    3    17.992,268
2024-03-31    4    17.916,588
2024-03-31    5    18.289,717
2024-03-31    6    18.463,949
2024-03-31    7    19.416,570
2024-03-31    8    20.887,066
2024-03-31    9    22.211,415
2024-03-31   10    23.125,865
2024-03-31   11    23.674,916
2024-03-31   12    23.604,826
2024-03-31   13    22.794,604
2024-03-31   14    21.560,751
2024-03-31   15    21.134,699
2024-03-31   16    20.905,291
2024-03-31   17    21.601,044
2024-03-31   18    23.387,511
2024-03-31   19    25.431,070
2024-03-31   20    26.148,988
2024-03-31   21    25.207,895
2024-03-31   22    23.564,680
2024-03-31   23    21.525,893

--- 2025-03-30 00:00:00 ---
      Data  Ora Totale Italia
2025-03-30    1      23.389,3
2025-03-30    2      21.994,3
2025-03-30    3      20.992,4
2025-03-30    4      20.838,7
2025-03-30    5      21.134,7
2025-03-30    6      21.760,0
2025-03-30    7      22.566,4
2025-03-30    8      24.041,2
2025-03-30    9      25.119,1
2025-03-30   10      26.355,1
2025-03-30   11      26.535,3
2025-03-30   12      26.763,0
2025-03-30   13      25.381,4
2025-03-30   14      24.281,5
2025-03-30   15      23.956,1
2025-03-30   16      24.158,3
2025-03-30   17      25.154,7
2025-03-30   18      27.308,5
2025-03-30   19      29.810,5
2025-03-30   20      29.875,4
2025-03-30   21      28.310,8
2025-03-30   22      26.254,3
2025-03-30   23      24.079,5

--- 2026-03-29 00:00:00 ---
      Data  Ora Totale Italia
2026-03-29    1      24.248,9
2026-03-29    2      23.092,1
2026-03-29    3      21.791,2
2026-03-29    4      21.919,9
2026-03-29    5      22.383,2
2026-03-29    6      23.067,9
2026-03-29    7      23.997,0
2026-03-29    8      25.268,4
2026-03-29    9      26.723,0
2026-03-29   10      27.528,4
2026-03-29   11      27.918,9
2026-03-29   12      28.234,7
2026-03-29   13      27.450,2
2026-03-29   14      26.919,5
2026-03-29   15      26.243,3
2026-03-29   16      25.496,4
2026-03-29   17      26.278,4
2026-03-29   18      28.733,8
2026-03-29   19      31.063,3
2026-03-29   20      31.372,3
2026-03-29   21      29.773,3
2026-03-29   22      27.653,0
2026-03-29   23      25.310,8

In [21]:
# autumn DST transition
autumn_dates = daily_periods.query('count == 25').index

for date in autumn_dates:
    print(f'\n--- {date} ---')
    print(
        load_data.loc[
            load_data['Data'] == date,
            ['Data', 'Ora', 'Totale Italia' ]
        ].to_string(index=False)
    )

--- 2015-10-25 00:00:00 ---
      Data  Ora Totale Italia
2015-10-25    1    23.852,901
2015-10-25    2    22.218,764
2015-10-25    3    21.386,027
2015-10-25    4    21.554,636
2015-10-25    5    20.973,890
2015-10-25    6    21.014,990
2015-10-25    7    21.935,183
2015-10-25    8    22.801,795
2015-10-25    9    23.609,703
2015-10-25   10    25.012,742
2015-10-25   11    25.824,848
2015-10-25   12    26.884,624
2015-10-25   13    26.322,012
2015-10-25   14    25.995,502
2015-10-25   15    24.602,485
2015-10-25   16    24.212,730
2015-10-25   17    24.051,622
2015-10-25   18    25.087,727
2015-10-25   19    27.783,242
2015-10-25   20    30.838,048
2015-10-25   21    32.384,403
2015-10-25   22    31.141,812
2015-10-25   23    29.482,083
2015-10-25   24    27.372,631
2015-10-25   25    24.897,960

--- 2016-10-30 00:00:00 ---
      Data  Ora Totale Italia
2016-10-30    1    23.979,491
2016-10-30    2    22.687,338
2016-10-30    3    21.430,453
2016-10-30    4    21.167,967
2016-10-30    5    20.850,743
2016-10-30    6    20.804,129
2016-10-30    7    21.233,916
2016-10-30    8    22.161,735
2016-10-30    9    22.767,201
2016-10-30   10    24.095,468
2016-10-30   11    25.280,249
2016-10-30   12    25.705,485
2016-10-30   13    25.762,377
2016-10-30   14    25.514,666
2016-10-30   15    24.148,755
2016-10-30   16    23.832,227
2016-10-30   17    24.059,064
2016-10-30   18    25.226,016
2016-10-30   19    27.258,093
2016-10-30   20    30.375,599
2016-10-30   21    31.585,261
2016-10-30   22    30.636,005
2016-10-30   23    29.052,553
2016-10-30   24    26.956,904
2016-10-30   25    24.082,296

--- 2017-10-29 00:00:00 ---
      Data  Ora Totale Italia
2017-10-29    1    23.682,163
2017-10-29    2    22.365,631
2017-10-29    3    21.227,135
2017-10-29    4    21.080,683
2017-10-29    5    20.830,514
2017-10-29    6    20.775,476
2017-10-29    7    21.290,581
2017-10-29    8    22.337,311
2017-10-29    9    23.688,923
2017-10-29   10    24.688,004
2017-10-29   11    25.299,222
2017-10-29   12    25.614,285
2017-10-29   13    25.642,541
2017-10-29   14    25.306,478
2017-10-29   15    24.084,475
2017-10-29   16    23.723,289
2017-10-29   17    24.280,129
2017-10-29   18    25.235,986
2017-10-29   19    26.887,703
2017-10-29   20    29.402,085
2017-10-29   21    31.126,436
2017-10-29   22    30.372,965
2017-10-29   23    28.803,317
2017-10-29   24    26.692,791
2017-10-29   25    24.236,930

--- 2018-10-28 00:00:00 ---
      Data  Ora Totale Italia
2018-10-28    1    24.764,527
2018-10-28    2    23.440,056
2018-10-28    3    22.454,346
2018-10-28    4    22.336,704
2018-10-28    5    22.013,346
2018-10-28    6    21.921,791
2018-10-28    7    22.294,316
2018-10-28    8    23.300,849
2018-10-28    9    24.602,072
2018-10-28   10    25.931,408
2018-10-28   11    26.854,840
2018-10-28   12    27.523,003
2018-10-28   13    27.755,372
2018-10-28   14    27.704,074
2018-10-28   15    26.356,766
2018-10-28   16    25.983,714
2018-10-28   17    26.280,769
2018-10-28   18    26.905,572
2018-10-28   19    27.786,517
2018-10-28   20    30.082,379
2018-10-28   21    32.094,602
2018-10-28   22    31.382,120
2018-10-28   23    29.630,227
2018-10-28   24    27.555,952
2018-10-28   25    24.863,313

--- 2019-10-27 00:00:00 ---
      Data  Ora Totale Italia
2019-10-27    1    24.151,441
2019-10-27    2    22.739,865
2019-10-27    3    21.993,391
2019-10-27    4    21.819,644
2019-10-27    5    21.364,215
2019-10-27    6    21.345,432
2019-10-27    7    21.756,328
2019-10-27    8    22.728,630
2019-10-27    9    23.550,304
2019-10-27   10    24.748,307
2019-10-27   11    25.745,578
2019-10-27   12    26.115,228
2019-10-27   13    26.166,575
2019-10-27   14    25.807,337
2019-10-27   15    24.726,815
2019-10-27   16    24.458,817
2019-10-27   17    24.789,742
2019-10-27   18    25.872,319
2019-10-27   19    27.286,002
2019-10-27   20    29.893,589
2019-10-27   21    31.365,099
2019-10-27   22    30.465,512
2019-10-27   23    28.720,536
2019-10-27   24    26.767,521
2019-10-27   25    24.085,912

--- 2020-10-25 00:00:00 ---
      Data  Ora Totale Italia
2020-10-25    1    23.332,281
2020-10-25    2    22.049,568
2020-10-25    3    21.243,409
2020-10-25    4    21.006,399
2020-10-25    5    20.520,413
2020-10-25    6    20.429,175
2020-10-25    7    20.965,824
2020-10-25    8    21.990,406
2020-10-25    9    23.073,990
2020-10-25   10    24.114,955
2020-10-25   11    25.062,660
2020-10-25   12    25.509,512
2020-10-25   13    25.682,898
2020-10-25   14    25.292,036
2020-10-25   15    24.161,732
2020-10-25   16    23.749,129
2020-10-25   17    24.129,858
2020-10-25   18    25.165,734
2020-10-25   19    27.077,262
2020-10-25   20    29.361,283
2020-10-25   21    30.553,191
2020-10-25   22    29.868,007
2020-10-25   23    27.958,281
2020-10-25   24    25.880,711
2020-10-25   25    23.444,608

--- 2021-10-31 00:00:00 ---
      Data  Ora Totale Italia
2021-10-31    1    23.907,390
2021-10-31    2    22.484,584
2021-10-31    3    21.608,998
2021-10-31    4    21.448,131
2021-10-31    5    21.087,527
2021-10-31    6    21.089,811
2021-10-31    7    21.572,974
2021-10-31    8    22.814,317
2021-10-31    9    23.810,478
2021-10-31   10    25.078,954
2021-10-31   11    26.323,415
2021-10-31   12    27.090,577
2021-10-31   13    27.589,845
2021-10-31   14    27.487,908
2021-10-31   15    26.286,857
2021-10-31   16    25.747,885
2021-10-31   17    25.915,209
2021-10-31   18    26.504,396
2021-10-31   19    28.165,849
2021-10-31   20    30.656,198
2021-10-31   21    31.892,949
2021-10-31   22    30.433,821
2021-10-31   23    28.560,193
2021-10-31   24    26.355,900
2021-10-31   25    24.290,345

--- 2022-10-30 00:00:00 ---
      Data  Ora Totale Italia
2022-10-30    1    22.586,946
2022-10-30    2    21.352,559
2022-10-30    3    20.657,931
2022-10-30    4    20.429,130
2022-10-30    5    20.199,256
2022-10-30    6    20.137,542
2022-10-30    7    20.484,267
2022-10-30    8    21.149,506
2022-10-30    9    21.993,494
2022-10-30   10    23.092,530
2022-10-30   11    24.059,313
2022-10-30   12    24.531,944
2022-10-30   13    24.719,476
2022-10-30   14    24.403,377
2022-10-30   15    23.459,072
2022-10-30   16    23.050,148
2022-10-30   17    23.435,902
2022-10-30   18    24.256,534
2022-10-30   19    26.099,023
2022-10-30   20    28.303,574
2022-10-30   21    29.413,911
2022-10-30   22    28.288,314
2022-10-30   23    26.673,049
2022-10-30   24    24.755,509
2022-10-30   25    22.464,382

--- 2023-10-29 00:00:00 ---
      Data  Ora Totale Italia
2023-10-29    1    23.131,669
2023-10-29    2    21.905,346
2023-10-29    3    21.206,866
2023-10-29    4    20.951,355
2023-10-29    5    20.728,944
2023-10-29    6    20.628,307
2023-10-29    7    20.987,256
2023-10-29    8    21.954,441
2023-10-29    9    22.831,282
2023-10-29   10    24.237,954
2023-10-29   11    25.106,050
2023-10-29   12    25.523,744
2023-10-29   13    25.768,399
2023-10-29   14    25.546,185
2023-10-29   15    24.724,414
2023-10-29   16    24.120,749
2023-10-29   17    24.183,991
2023-10-29   18    25.099,546
2023-10-29   19    26.387,444
2023-10-29   20    28.456,396
2023-10-29   21    29.678,501
2023-10-29   22    28.620,468
2023-10-29   23    26.850,304
2023-10-29   24    24.991,002
2023-10-29   25    22.645,517

--- 2024-10-27 00:00:00 ---
      Data  Ora Totale Italia
2024-10-27    1    23.066,873
2024-10-27    2    21.856,813
2024-10-27    3    21.024,040
2024-10-27    4    20.825,582
2024-10-27    5    20.524,413
2024-10-27    6    20.525,069
2024-10-27    7    20.994,950
2024-10-27    8    22.003,768
2024-10-27    9    23.014,750
2024-10-27   10    24.248,830
2024-10-27   11    25.577,550
2024-10-27   12    26.141,775
2024-10-27   13    26.559,505
2024-10-27   14    26.747,614
2024-10-27   15    25.671,842
2024-10-27   16    24.807,211
2024-10-27   17    24.663,851
2024-10-27   18    25.335,322
2024-10-27   19    26.953,854
2024-10-27   20    29.086,532
2024-10-27   21    30.372,045
2024-10-27   22    28.964,776
2024-10-27   23    27.410,181
2024-10-27   24    25.671,921
2024-10-27   25    23.495,107

--- 2025-10-26 00:00:00 ---
      Data  Ora Totale Italia
2025-10-26    1      23.704,2
2025-10-26    2      22.381,7
2025-10-26    3      21.793,6
2025-10-26    4      21.448,8
2025-10-26    5      21.400,7
2025-10-26    6      21.337,1
2025-10-26    7      21.825,5
2025-10-26    8      22.782,8
2025-10-26    9      23.282,9
2025-10-26   10      24.321,4
2025-10-26   11      25.706,0
2025-10-26   12      25.963,4
2025-10-26   13      26.272,4
2025-10-26   14      26.516,2
2025-10-26   15      25.495,7
2025-10-26   16      24.860,3
2025-10-26   17      25.033,4
2025-10-26   18      25.962,9
2025-10-26   19      27.422,3
2025-10-26   20      29.734,1
2025-10-26   21      30.955,7
2025-10-26   22      29.671,6
2025-10-26   23      28.085,7
2025-10-26   24      26.261,3
2025-10-26   25      24.101,0

In [22]:
load_data['datetime'] = (
    load_data['Data']
    + pd.to_timedelta(load_data['Ora'] - 1, unit='h')
)

diffs = load_data['datetime'].diff()

diffs.value_counts().sort_index()

datetime
0 days 00:00:00        11
0 days 01:00:00    100751
0 days 02:00:00        12
Name: count, dtype: int64

Source for period meaning for GME: https://gme.mercatoelettrico.org/Portals/0/Documents/it-IT/20250101DTF01rev3MPE.pdf

In [23]:
# make a copy
load_data = load_data.copy()

# convert Date
load_data['Date'] = pd.to_datetime(
    load_data['Data'],
    dayfirst=True,
    errors='coerce'
)

# make sure Ora is numeric
load_data['Ora'] = pd.to_numeric(
    load_data['Ora'],
    errors='coerce'
)

In [24]:
periods_per_day = (
    load_data
    .groupby('Date')['Ora']
    .transform('count')
)

load_data['periods_per_day'] = periods_per_day

In [25]:
def gme_local_datetime(row):
    date = row['Date']
    hour = row['Ora']
    periods = row['periods_per_day']

    # normal day: 24 periods
    if periods == 24:
        return date + pd.to_timedelta(hour - 1, unit='h')

    # spring DST: 23 periods
    # Ora 1 = 00:00
    # Ora 2 = 01:00
    # Ora 3 = 03:00
    elif periods == 23:
        if hour >= 3:
            return date + pd.to_timedelta(hour, unit='h')
        else:
            return date + pd.to_timedelta(hour - 1, unit='h')

    # Autumn DST: 25 periods
    # Ora 1 = 00:00
    # Ora 2 = 01:00
    # Ora 3 = 02:00 CEST
    # Ora 4 = 02:00 CET
    # Ora 5 = 03:00 CET
    elif periods == 25:
        if hour <= 2:
            return date + pd.to_timedelta(hour - 1, unit='h')
        elif hour <= 4:
            return date + pd.Timedelta(hours=2)
        else:
            return date + pd.to_timedelta(hour - 2, unit='h')

    else:
        raise ValueError(
            f"Unexpected number of periods ({periods}) for {date}"
        )

In [26]:
load_data['datetime_local_naive'] = load_data.apply(
    gme_local_datetime,
    axis=1
)

In [27]:
ambiguous = (
    (load_data['periods_per_day'] == 25)
    & (load_data['Ora'] == 3)
)

load_data['datetime_local'] = (
    load_data['datetime_local_naive']
    .dt.tz_localize(
        'Europe/Rome',
        ambiguous=ambiguous,
        nonexistent='raise'
    )
)

In [28]:
load_data['datetime_UTC'] = (
    load_data['datetime_local']
    .dt.tz_convert('UTC')
)

In [29]:
load_data.head()

,Data,Ora,Centro Nord,Centro Sud,Nord,Sardegna,Sicilia,Sud,Totale Italia,Calabria,datetime,Date,periods_per_day,datetime_local_naive,datetime_local,datetime_UTC
0,2015-01-01,1,"2.670,851","4.590,186","10.774,037",997.138,"1.930,829","2.347,270","23.310,311",NaN,2015-01-01 00:00:00,2015-01-01,24,2015-01-01 00:00:00,2015-01-01 00:00:00+01:00,2014-12-31 23:00:00+00:00
1,2015-01-01,2,"2.513,713","4.342,739","10.576,993",951.110,"1.821,231","2.213,368","22.419,154",NaN,2015-01-01 01:00:00,2015-01-01,24,2015-01-01 01:00:00,2015-01-01 01:00:00+01:00,2015-01-01 00:00:00+00:00
2,2015-01-01,3,"2.392,789","4.028,419","10.169,339",903.001,"1.769,136","2.031,384","21.294,068",NaN,2015-01-01 02:00:00,2015-01-01,24,2015-01-01 02:00:00,2015-01-01 02:00:00+01:00,2015-01-01 01:00:00+00:00
3,2015-01-01,4,"2.259,362","3.732,403","9.769,460",855.196,"1.673,111","1.869,842","20.159,374",NaN,2015-01-01 03:00:00,2015-01-01,24,2015-01-01 03:00:00,2015-01-01 03:00:00+01:00,2015-01-01 02:00:00+00:00
4,2015-01-01,5,"2.245,990","3.363,157","9.613,212",855.747,"1.536,739","1.761,414","19.376,259",NaN,2015-01-01 04:00:00,2015-01-01,24,2015-01-01 04:00:00,2015-01-01 04:00:00+01:00,2015-01-01 03:00:00+00:00

In [30]:
load_data.loc[
    load_data['Date'] == '2015-10-25',
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'      Date  Ora            datetime_local              datetime_UTC\n2015-10-25    1 2015-10-25 00:00:00+02:00 2015-10-24 22:00:00+00:00\n2015-10-25    2 2015-10-25 01:00:00+02:00 2015-10-24 23:00:00+00:00\n2015-10-25    3 2015-10-25 02:00:00+02:00 2015-10-25 00:00:00+00:00\n2015-10-25    4 2015-10-25 02:00:00+01:00 2015-10-25 01:00:00+00:00\n2015-10-25    5 2015-10-25 03:00:00+01:00 2015-10-25 02:00:00+00:00\n2015-10-25    6 2015-10-25 04:00:00+01:00 2015-10-25 03:00:00+00:00\n2015-10-25    7 2015-10-25 05:00:00+01:00 2015-10-25 04:00:00+00:00\n2015-10-25    8 2015-10-25 06:00:00+01:00 2015-10-25 05:00:00+00:00\n2015-10-25    9 2015-10-25 07:00:00+01:00 2015-10-25 06:00:00+00:00\n2015-10-25   10 2015-10-25 08:00:00+01:00 2015-10-25 07:00:00+00:00\n2015-10-25   11 2015-10-25 09:00:00+01:00 2015-10-25 08:00:00+00:00\n2015-10-25   12 2015-10-25 10:00:00+01:00 2015-10-25 09:00:00+00:00\n2015-10-25   13 2015-10-25 11:00:00+01:00 2015-10-25 10:00:00+00:00\n2015-10-25   14 2015-10-25 12:00:00+01:00 2015-10-25 11:00:00+00:00\n2015-10-25   15 2015-10-25 13:00:00+01:00 2015-10-25 12:00:00+00:00\n2015-10-25   16 2015-10-25 14:00:00+01:00 2015-10-25 13:00:00+00:00\n2015-10-25   17 2015-10-25 15:00:00+01:00 2015-10-25 14:00:00+00:00\n2015-10-25   18 2015-10-25 16:00:00+01:00 2015-10-25 15:00:00+00:00\n2015-10-25   19 2015-10-25 17:00:00+01:00 2015-10-25 16:00:00+00:00\n2015-10-25   20 2015-10-25 18:00:00+01:00 2015-10-25 17:00:00+00:00\n2015-10-25   21 2015-10-25 19:00:00+01:00 2015-10-25 18:00:00+00:00\n2015-10-25   22 2015-10-25 20:00:00+01:00 2015-10-25 19:00:00+00:00\n2015-10-25   23 2015-10-25 21:00:00+01:00 2015-10-25 20:00:00+00:00\n2015-10-25   24 2015-10-25 22:00:00+01:00 2015-10-25 21:00:00+00:00\n2015-10-25   25 2015-10-25 23:00:00+01:00 2015-10-25 22:00:00+00:00'

In [31]:
load_data['datetime_UTC'].diff().value_counts().head()

datetime_UTC
0 days 01:00:00    100774
Name: count, dtype: int64

In [32]:
load_data.loc[
    load_data['Date'].isin([
        '2015-03-29',
        '2015-10-25',
        '2015-10-26'
    ]),
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'Empty DataFrame\nColumns: [Date, Ora, datetime_local, datetime_UTC]\nIndex: []'

In [33]:
print(
    load_data['datetime_UTC'].isna().sum()
)

0

In [34]:
load_data = load_data.drop(
    columns=['periods_per_day', 'datetime_local_naive']
)

In [35]:
load_data = load_data[
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
    + [
        col for col in load_data.columns
        if col not in [
            'Date',
            'Ora',
            'datetime_local',
            'datetime_UTC'
        ]
    ]
]

In [36]:
load_data[
    load_data['Date'].dt.strftime('%Y-%m-%d') == '2015-03-29'
][['Date', 'Ora', 'datetime_local', 'datetime_UTC']]

           Date  Ora            datetime_local              datetime_UTC
2088 2015-03-29    1 2015-03-29 00:00:00+01:00 2015-03-28 23:00:00+00:00
2089 2015-03-29    2 2015-03-29 01:00:00+01:00 2015-03-29 00:00:00+00:00
2090 2015-03-29    3 2015-03-29 03:00:00+02:00 2015-03-29 01:00:00+00:00
2091 2015-03-29    4 2015-03-29 04:00:00+02:00 2015-03-29 02:00:00+00:00
2092 2015-03-29    5 2015-03-29 05:00:00+02:00 2015-03-29 03:00:00+00:00
2093 2015-03-29    6 2015-03-29 06:00:00+02:00 2015-03-29 04:00:00+00:00
2094 2015-03-29    7 2015-03-29 07:00:00+02:00 2015-03-29 05:00:00+00:00
2095 2015-03-29    8 2015-03-29 08:00:00+02:00 2015-03-29 06:00:00+00:00
2096 2015-03-29    9 2015-03-29 09:00:00+02:00 2015-03-29 07:00:00+00:00
2097 2015-03-29   10 2015-03-29 10:00:00+02:00 2015-03-29 08:00:00+00:00
2098 2015-03-29   11 2015-03-29 11:00:00+02:00 2015-03-29 09:00:00+00:00
2099 2015-03-29   12 2015-03-29 12:00:00+02:00 2015-03-29 10:00:00+00:00
2100 2015-03-29   13 2015-03-29 13:00:00+02:00 2015-03-29 11:00:00+00:00
2101 2015-03-29   14 2015-03-29 14:00:00+02:00 2015-03-29 12:00:00+00:00
2102 2015-03-29   15 2015-03-29 15:00:00+02:00 2015-03-29 13:00:00+00:00
2103 2015-03-29   16 2015-03-29 16:00:00+02:00 2015-03-29 14:00:00+00:00
2104 2015-03-29   17 2015-03-29 17:00:00+02:00 2015-03-29 15:00:00+00:00
2105 2015-03-29   18 2015-03-29 18:00:00+02:00 2015-03-29 16:00:00+00:00
2106 2015-03-29   19 2015-03-29 19:00:00+02:00 2015-03-29 17:00:00+00:00
2107 2015-03-29   20 2015-03-29 20:00:00+02:00 2015-03-29 18:00:00+00:00
2108 2015-03-29   21 2015-03-29 21:00:00+02:00 2015-03-29 19:00:00+00:00
2109 2015-03-29   22 2015-03-29 22:00:00+02:00 2015-03-29 20:00:00+00:00
2110 2015-03-29   23 2015-03-29 23:00:00+02:00 2015-03-29 21:00:00+00:00

In [37]:
load_data.loc[
    load_data['Date'].dt.strftime('%Y-%m-%d') == '2015-03-29',
    ['Date', 'Ora', 'datetime_local', 'datetime_UTC']
].to_string(index=False)

'      Date  Ora            datetime_local              datetime_UTC\n2015-03-29    1 2015-03-29 00:00:00+01:00 2015-03-28 23:00:00+00:00\n2015-03-29    2 2015-03-29 01:00:00+01:00 2015-03-29 00:00:00+00:00\n2015-03-29    3 2015-03-29 03:00:00+02:00 2015-03-29 01:00:00+00:00\n2015-03-29    4 2015-03-29 04:00:00+02:00 2015-03-29 02:00:00+00:00\n2015-03-29    5 2015-03-29 05:00:00+02:00 2015-03-29 03:00:00+00:00\n2015-03-29    6 2015-03-29 06:00:00+02:00 2015-03-29 04:00:00+00:00\n2015-03-29    7 2015-03-29 07:00:00+02:00 2015-03-29 05:00:00+00:00\n2015-03-29    8 2015-03-29 08:00:00+02:00 2015-03-29 06:00:00+00:00\n2015-03-29    9 2015-03-29 09:00:00+02:00 2015-03-29 07:00:00+00:00\n2015-03-29   10 2015-03-29 10:00:00+02:00 2015-03-29 08:00:00+00:00\n2015-03-29   11 2015-03-29 11:00:00+02:00 2015-03-29 09:00:00+00:00\n2015-03-29   12 2015-03-29 12:00:00+02:00 2015-03-29 10:00:00+00:00\n2015-03-29   13 2015-03-29 13:00:00+02:00 2015-03-29 11:00:00+00:00\n2015-03-29   14 2015-03-29 14:00:00+02:00 2015-03-29 12:00:00+00:00\n2015-03-29   15 2015-03-29 15:00:00+02:00 2015-03-29 13:00:00+00:00\n2015-03-29   16 2015-03-29 16:00:00+02:00 2015-03-29 14:00:00+00:00\n2015-03-29   17 2015-03-29 17:00:00+02:00 2015-03-29 15:00:00+00:00\n2015-03-29   18 2015-03-29 18:00:00+02:00 2015-03-29 16:00:00+00:00\n2015-03-29   19 2015-03-29 19:00:00+02:00 2015-03-29 17:00:00+00:00\n2015-03-29   20 2015-03-29 20:00:00+02:00 2015-03-29 18:00:00+00:00\n2015-03-29   21 2015-03-29 21:00:00+02:00 2015-03-29 19:00:00+00:00\n2015-03-29   22 2015-03-29 22:00:00+02:00 2015-03-29 20:00:00+00:00\n2015-03-29   23 2015-03-29 23:00:00+02:00 2015-03-29 21:00:00+00:00'

In [39]:
load_data.columns

Index(['Date', 'Ora', 'datetime_local', 'datetime_UTC', 'Data', 'Centro Nord',
       'Centro Sud', 'Nord', 'Sardegna', 'Sicilia', 'Sud', 'Totale Italia',
       'Calabria', 'datetime'],
      dtype='str')

In [40]:
load_data = load_data.drop(
    columns=['Data', 'datetime']
)

In [41]:
# final cleaning check
load_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            100775 non-null  datetime64[us]
 1   Ora             100775 non-null  int64
 2   datetime_local  100775 non-null  datetime64[us, Europe/Rome]
 3   datetime_UTC    100775 non-null  datetime64[us, UTC]
 4   Centro Nord     100775 non-null  str
 5   Centro Sud      100775 non-null  str
 6   Nord            100775 non-null  str
 7   Sardegna        100775 non-null  str
 8   Sicilia         100775 non-null  str
 9   Sud             100775 non-null  str
 10  Totale Italia   100775 non-null  str
 11  Calabria        48167 non-null   object
dtypes: datetime64[us, Europe/Rome](1), datetime64[us, UTC](1), datetime64[us](1), int64(1), object(1), str(7)
memory usage: 9.2+ MB

In [46]:
loads = load_data.columns[4:]

for load in loads:
    load_data[load] = (
        load_data[load]
        .str.replace('.', '', regex=False)
        .str.replace(',', '.', regex=False)
        .astype(float)
    )

In [48]:
load_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100775 entries, 0 to 100774
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            100775 non-null  datetime64[us]
 1   Ora             100775 non-null  int64
 2   datetime_local  100775 non-null  datetime64[us, Europe/Rome]
 3   datetime_UTC    100775 non-null  datetime64[us, UTC]
 4   Centro Nord     100775 non-null  float64
 5   Centro Sud      100775 non-null  float64
 6   Nord            100775 non-null  float64
 7   Sardegna        100775 non-null  float64
 8   Sicilia         100775 non-null  float64
 9   Sud             100775 non-null  float64
 10  Totale Italia   100775 non-null  float64
 11  Calabria        43824 non-null   float64
dtypes: datetime64[us, Europe/Rome](1), datetime64[us, UTC](1), datetime64[us](1), float64(8), int64(1)
memory usage: 9.2 MB

In [50]:
load_data.columns.tolist()

['Date',
 'Ora',
 'datetime_local',
 'datetime_UTC',
 'Centro Nord',
 'Centro Sud',
 'Nord',
 'Sardegna',
 'Sicilia',
 'Sud',
 'Totale Italia',
 'Calabria']

In [51]:
from pathlib import Path

output_path = Path('../dataset/clean/load')

# create folder if non-existent
output_path.mkdir(parents=True, exist_ok=True)

# save in CSV format
load_data.to_csv(output_path / 'load-clean.csv', index=False)